#pragma checksum "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "73B8A80C1FFEE059515B0F9AE585AE4D58C93880B7824AAD2856CE584FA50AE9"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using CallCenterSecure;
    
    
    public class _Page_Views_Home_TicketManagementEdit_cshtml : System.Web.Mvc.WebViewPage<CallCenter.Models.TicketManagementModel> {
        
#line hidden
        
        public _Page_Views_Home_TicketManagementEdit_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
  
    ViewBag.Title = "TicketManagementEdit";

            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 96, 12, true);

WriteLiteral("\n    <script");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 96, 12, true);

WriteAttribute("src", Tuple.Create(" src=\"", 108), Tuple.Create("\"", 143)
, Tuple.Create(Tuple.Create("", 114), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-3.3.1.min.js")
, 114), false)
);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 144, 33, true);

WriteLiteral("></script>\n<h2>Edit Ticket</h2>\n\n");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 144, 33, true);

            
            #line 9 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
 using (Html.BeginForm())
{
    


            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 211, 4, true);

WriteLiteral("<div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 211, 4, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 215, 24, true);

WriteLiteral(" class=\"form-horizontal\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 215, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 239, 3, true);

WriteLiteral(">\n\n");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 239, 3, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 242, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 242, 4, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 247, 64, false);

            
            #line 15 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 247, 64, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 311, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 311, 1, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 312, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 312, 4, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 317, 39, false);

            
            #line 16 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
Write(Html.HiddenFor(model => model.TicketId));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 317, 39, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 356, 9, true);

WriteLiteral("\n    <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 356, 9, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 365, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 365, 23, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 388, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 388, 14, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 402, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 402, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 419, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 419, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 437, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 437, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 455, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 455, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 458, 86, false);

            
            #line 19 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.Label("Name", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 458, 86, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 544, 23, true);

WriteLiteral("</div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 544, 23, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 567, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 567, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 585, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 585, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 588, 93, false);

            
            #line 20 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 588, 93, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 681, 23, true);

WriteLiteral("</div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 681, 23, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 704, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 704, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 722, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 722, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 725, 98, false);

            
            #line 21 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 725, 98, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 823, 34, true);

WriteLiteral("</div>\n        </div>\n        <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 823, 34, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 857, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 857, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 874, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 874, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 892, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 892, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 910, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 910, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 913, 96, false);

            
            #line 24 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.Label("Calling Number", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 913, 96, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1009, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1009, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1033, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1033, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1051, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1051, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1054, 102, false);

            
            #line 25 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.EditorFor(model => model.CallingNumber, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1054, 102, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1156, 23, true);

WriteLiteral("</div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1156, 23, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1179, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1179, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1197, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1197, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1200, 107, false);

            
            #line 26 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.CallingNumber, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1200, 107, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1307, 41, true);

WriteLiteral("</div>\n        </div>\n    </div>\n    <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1307, 41, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1348, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1348, 23, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1371, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1371, 14, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1385, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1385, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1402, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1402, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1420, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1420, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1438, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1438, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1441, 96, false);

            
            #line 31 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.Label("Type Of Caller", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1441, 96, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1537, 23, true);

WriteLiteral("</div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1537, 23, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1560, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1560, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1578, 22, true);

WriteLiteral(">\n                <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1578, 22, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1600, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1600, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1617, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1617, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1620, 125, false);

            
            #line 33 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                                  Write(Html.RadioButtonFor(model => model.TypeOfCaller, "Agent", new { @class = "form-control redioButton", @checked = "@checked" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1620, 125, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1745, 5, true);

WriteLiteral("<span");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1745, 5, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1750, 24, true);

WriteLiteral(" class=\"redioButtonText\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1750, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1774, 41, true);

WriteLiteral(">Agent</span> </div>\n                <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1774, 41, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1815, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1815, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1832, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1832, 1, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1834, 103, false);

            
            #line 34 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                                 Write(Html.RadioButtonFor(model => model.TypeOfCaller, "Member", new { @class = "form-control redioButton" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1834, 103, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1937, 5, true);

WriteLiteral("<span");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1937, 5, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1942, 24, true);

WriteLiteral(" class=\"redioButtonText\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1942, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 1966, 41, true);

WriteLiteral(">Member</span></div>\n                <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 1966, 41, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2007, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2007, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2024, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2024, 1, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2026, 102, false);

            
            #line 35 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                                 Write(Html.RadioButtonFor(model => model.TypeOfCaller, "Other", new { @class = "form-control redioButton" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2026, 102, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2128, 5, true);

WriteLiteral("<span");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2128, 5, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2133, 24, true);

WriteLiteral(" class=\"redioButtonText\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2133, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2157, 55, true);

WriteLiteral(">Other</span></div>\n            </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2157, 55, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2212, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2212, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2230, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2230, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2233, 106, false);

            
            #line 37 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.TypeOfCaller, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2233, 106, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2339, 34, true);

WriteLiteral("</div>\n        </div>\n        <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2339, 34, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2373, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2373, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2390, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2390, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2408, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2408, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2426, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2426, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2429, 93, false);

            
            #line 40 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.Label("Client Type", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2429, 93, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2522, 23, true);

WriteLiteral("</div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2522, 23, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2545, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2545, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2563, 22, true);

WriteLiteral(">\n                <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2563, 22, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2585, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2585, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2602, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2602, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2605, 113, false);

            
            #line 42 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                                  Write(Html.RadioButtonFor(model => model.ClientType, "Corporate Solution", new { @class = "form-control redioButton" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2605, 113, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2718, 5, true);

WriteLiteral("<span");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2718, 5, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2723, 24, true);

WriteLiteral(" class=\"redioButtonText\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2723, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2747, 54, true);

WriteLiteral(">Corporate Solution</span> </div>\n                <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2747, 54, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2801, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2801, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2818, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2818, 1, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2820, 105, false);

            
            #line 43 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                                 Write(Html.RadioButtonFor(model => model.ClientType, "Individual", new { @class = "form-control redioButton" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2820, 105, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2925, 5, true);

WriteLiteral("<span");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2925, 5, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2930, 24, true);

WriteLiteral(" class=\"redioButtonText\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2930, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 2954, 60, true);

WriteLiteral(">Individual</span></div>\n            </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 2954, 60, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3014, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3014, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3032, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3032, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3035, 104, false);

            
            #line 45 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.ClientType, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3035, 104, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3139, 50, true);

WriteLiteral("</div>\n        </div>\n       \n    </div>\n\n    <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3139, 50, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3189, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3189, 23, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3212, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3212, 14, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3226, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3226, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3243, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3243, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3261, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3261, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3279, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3279, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3282, 95, false);

            
            #line 52 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.Label("Policy Number", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3282, 95, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3377, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3377, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3401, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3401, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3419, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3419, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3422, 101, false);

            
            #line 53 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.EditorFor(model => model.PolicyNumber, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3422, 101, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3523, 23, true);

WriteLiteral("</div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3523, 23, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3546, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3546, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3564, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3564, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3567, 106, false);

            
            #line 54 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.PolicyNumber, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3567, 106, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3673, 34, true);

WriteLiteral("</div>\n        </div>\n        <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3673, 34, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3707, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3707, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3724, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3724, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3742, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3742, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3760, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3760, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3763, 89, false);

            
            #line 57 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.Label("Segment", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3763, 89, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3852, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3852, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3876, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3876, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3894, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3894, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3896, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3896, 16, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 3913, 288, false);

            
            #line 59 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
           Write(Html.DropDownListFor(model => model.CustomerSegment, new List<SelectListItem>
                {
                new SelectListItem{ Text="Primer", Value = "Primer" },
                new SelectListItem{ Text="Elite", Value = "Elite" },
                 }, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 3913, 288, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4201, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4201, 36, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4237, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4237, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4255, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4255, 1, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4257, 109, false);

            
            #line 65 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                              Write(Html.ValidationMessageFor(model => model.CustomerSegment, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4257, 109, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4366, 41, true);

WriteLiteral("</div>\n        </div>\n    </div>\n    <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4366, 41, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4407, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4407, 23, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4430, 15, true);

WriteLiteral(">\n\n        <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4430, 15, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4445, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4445, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4462, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4462, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4480, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4480, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4498, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4498, 1, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4500, 94, false);

            
            #line 71 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                              Write(Html.Label("Type Of Call", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4500, 94, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4594, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4594, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4618, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4618, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4636, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4636, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4638, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4638, 16, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 4655, 349, false);

            
            #line 73 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
           Write(Html.DropDownListFor(model => model.TypeOfCall, new List<SelectListItem>
           {
               new SelectListItem{ Text="Query", Value = "Query" },
               new SelectListItem{ Text="Request", Value = "Request" },
               new SelectListItem{ Text="Complaint", Value = "Complaint" },
            }, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 4655, 349, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5004, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5004, 36, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5040, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5040, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5058, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5058, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5061, 104, false);

            
            #line 80 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.TypeOfCall, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5061, 104, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5165, 35, true);

WriteLiteral(" </div>\n        </div>\n        <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5165, 35, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5200, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5200, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5217, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5217, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5235, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5235, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5253, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5253, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5256, 90, false);

            
            #line 83 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.Label("Category", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5256, 90, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5346, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5346, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5370, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5370, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5388, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5388, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5391, 144, false);

            
            #line 84 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.DropDownListFor(model => model.Category, new SelectList(Model.CategoryList, "CategoryId", "CategoryName"), new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5391, 144, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5535, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5535, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5559, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5559, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5577, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5577, 1, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5579, 102, false);

            
            #line 85 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                              Write(Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5579, 102, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5681, 42, true);

WriteLiteral(" </div>\n        </div>\n    </div>\n    <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5681, 42, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5723, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5723, 23, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5746, 15, true);

WriteLiteral(">\n\n        <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5746, 15, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5761, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5761, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5778, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5778, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5796, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5796, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5814, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5814, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5817, 94, false);

            
            #line 91 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.Label("Sub Category", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5817, 94, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5911, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5911, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5935, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5935, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5953, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5953, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 5956, 156, false);

            
            #line 92 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.DropDownListFor(model => model.SubCategory, new SelectList(Model.SubCategoryList, "SubCategoryId", "SubCategoryName"), new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 5956, 156, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6112, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6112, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6136, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6136, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6154, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6154, 1, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6156, 105, false);

            
            #line 93 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                              Write(Html.ValidationMessageFor(model => model.SubCategory, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6156, 105, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6261, 35, true);

WriteLiteral(" </div>\n        </div>\n        <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6261, 35, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6296, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6296, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6313, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6313, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6331, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6331, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6349, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6349, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6352, 98, false);

            
            #line 96 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.Label("Sub Sub Category", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6352, 98, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6450, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6450, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6474, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6474, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6492, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6492, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6495, 168, false);

            
            #line 97 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.DropDownListFor(model => model.SubSubCategory, new SelectList(Model.SubSubCategoryList, "SubSubCategoryId", "SubSubCategoryName"), new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6495, 168, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6663, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6663, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6687, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6687, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6705, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6705, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6708, 92, false);

            
            #line 98 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.SubSubCategory, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6708, 92, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6800, 43, true);

WriteLiteral(" </div>\n        </div>\n    </div>\n\n    <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6800, 43, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6843, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6843, 23, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6866, 15, true);

WriteLiteral(">\n\n        <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6866, 15, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6881, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6881, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6898, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6898, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6916, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6916, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6934, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6934, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 6937, 88, false);

            
            #line 105 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.Label("Status", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 6937, 88, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7025, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7025, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7049, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7049, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7067, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7067, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7069, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7069, 16, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7086, 547, false);

            
            #line 107 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
           Write(Html.DropDownListFor(model => model.Status, new SelectList(new[] { new SelectListItem { Text = "Open", Value = "Open" },
                                                                                     new SelectListItem { Text = "InProgress", Value = "InProgress" },
                                                                                     new SelectListItem { Text = "Closed", Value = "Closed" }
                                                                                }, "Text", "Value"), new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7086, 547, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7633, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7633, 36, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7669, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7669, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7687, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7687, 1, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7689, 100, false);

            
            #line 112 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                              Write(Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7689, 100, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7789, 35, true);

WriteLiteral(" </div>\n        </div>\n        <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7789, 35, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7824, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7824, 17, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7841, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7841, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7859, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7859, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7877, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7877, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7880, 88, false);

            
            #line 115 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.Label("Remark", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7880, 88, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7968, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7968, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 7992, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 7992, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8010, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8010, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8013, 113, false);

            
            #line 116 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.EditorFor(model => model.Remark, new { htmlAttributes = new { @class = "form-control paddingBottom10px" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8013, 113, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8126, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8126, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8150, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8150, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8168, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8168, 2, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8171, 100, false);

            
            #line 117 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8171, 100, false);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8271, 48, true);

WriteLiteral(" </div>\n        </div>\n    </div>\n     \n    <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8271, 48, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8319, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8319, 23, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8342, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8342, 14, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8356, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8356, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8374, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8374, 18, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8392, 25, true);

WriteLiteral(" class=\"savecancelbutton\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8392, 25, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8417, 24, true);

WriteLiteral(">\n                <input");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8417, 24, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8441, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8441, 14, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8455, 13, true);

WriteLiteral(" value=\"Save\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8455, 13, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8468, 41, true);

WriteLiteral(" class=\"btn btn-primary marginright100px\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8468, 41, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8509, 26, true);

WriteLiteral(" />\n                <input");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8509, 26, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8535, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8535, 14, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8549, 15, true);

WriteLiteral(" value=\"Cancel\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8549, 15, true);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8564, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8564, 24, true);

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 8588), Tuple.Create("\"", 8651)
, Tuple.Create(Tuple.Create("", 8598), Tuple.Create("window.location=", 8598), true)
, Tuple.Create(Tuple.Create(" ", 8614), Tuple.Create("\'", 8615), true)
            
            #line 125 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
                       , Tuple.Create(Tuple.Create("", 8616), Tuple.Create<System.Object, System.Int32>(Url.Action( "TicketList", "Home")
            
            #line default
            #line hidden
, 8616), false)
, Tuple.Create(Tuple.Create("", 8650), Tuple.Create("\'", 8650), true)
);

BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8652, 57, true);

WriteLiteral(" />\n\n            </div>\n        </div>\n    </div>\n</div>\n");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8652, 57, true);

            
            #line 131 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagementEdit.cshtml"
}

            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketManagementEdit.cshtml", 8711, 2650, true);

WriteLiteral("\n<script>\n    $(document).ready(function () {\n        $(\"#Category\").on(\"change\"," +
" function () {\n            fillSubCategoryDropdown();\n        });\n        $(\"#Su" +
"bCategory\").on(\"change\", function () {\n            fillSubSubCategoryDropdown();" +
"\n        });\n        function fillSubCategoryDropdown() {\n            $.ajax(\n  " +
"              {\n                    url: \'/Home/GetSubCategoryByCategory?Categor" +
"yId=\' + $(\"#Category\").val(),\n                    type: \'GET\',\n                 " +
"   data: \"\",\n                    contentType: \'application/json; charset=utf-8\'," +
"\n                    success: function (data) {\n                        var subc" +
"at = $.parseJSON(data);\n                        $(\"#SubCategory\").html(\"\");\n    " +
"                    for (var i = 0; i < subcat.length; i++) {\n                  " +
"          $(\"#SubCategory\").append(\"<option value=\'\" + subcat[i].SubCategoryId +" +
" \"\'>\" + subcat[i].SubCategoryName + \"</option>\");\n                        }\n    " +
"                    fillSubSubCategoryDropdown();\n                    },\n       " +
"             error: function () {\n                        alert(\"error\");\n      " +
"              }\n                })\n        }\n\n        function fillSubSubCategor" +
"yDropdown() {\n            $.ajax(\n                {\n                    url: \'/H" +
"ome/GetSubSubCategoryBySubCategory?SubCategoryId=\' + $(\"#SubCategory\").val(),\n  " +
"                  type: \'GET\',\n                    data: \"\",\n                   " +
" contentType: \'application/json; charset=utf-8\',\n                    success: fu" +
"nction (data) {\n                        var subcat = $.parseJSON(data);\n        " +
"                $(\"#SubSubCategory\").html(\"\");\n                        for (var " +
"i = 0; i < subcat.length; i++) {\n                            $(\"#SubSubCategory\"" +
").append(\"<option value=\'\" + subcat[i].SubSubCategoryId + \"\'>\" + subcat[i].SubSu" +
"bCategoryName + \"</option>\");\n                        }\n                    },\n " +
"                   error: function () {\n                        alert(\"error\");\n" +
"                    }\n                });\n        }\n\n        $(document).on(\"cha" +
"nge\", \"#TypeOfCaller\", function () {\n\n            $(\"#CustomerSegment\").html(\"\")" +
";\n            if ($(\"#TypeOfCaller:checked\").val() == \"Agent\") {\n               " +
" $(\"#CustomerSegment\").append(\"<option value=\'Primer\'>Primer</option>\");\n       " +
"         $(\"#CustomerSegment\").append(\"<option value=\'Elite\'>Elite</option>\");\n " +
"           }\n            else {\n                $(\"#CustomerSegment\").append(\"<o" +
"ption value=\'Normal\'>Normal</option>\");\n                $(\"#CustomerSegment\").ap" +
"pend(\"<option value=\'Ruby\'>Ruby</option>\");\n            }\n        });\n\n    });\n<" +
"/script>\n");

EndContext("~/Views/Home/TicketManagementEdit.cshtml", 8711, 2650, true);

        }
    }
}
