#pragma checksum "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "A4525A0CB36932B3C55242AA5C8FF0EE28BFA5069AABA4AB27414FF3224F6CEE"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using CallCenterSecure;
    
    
    public class _Page_Views_Home_TicketList_cshtml : System.Web.Mvc.WebViewPage<CallCenter.Models.TicketManagementModel> {
        
#line hidden
        
        public _Page_Views_Home_TicketList_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
  
    ViewBag.Title = "Ticket List";

            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketList.cshtml", 88, 6, true);

WriteLiteral("\n<link");

EndContext("~/Views/Home/TicketList.cshtml", 88, 6, true);

WriteAttribute("href", Tuple.Create(" href=\"", 94), Tuple.Create("\"", 124)
, Tuple.Create(Tuple.Create("", 101), Tuple.Create<System.Object, System.Int32>(Href("~/Content/jquery-ui.css")
, 101), false)
);

BeginContext("~/Views/Home/TicketList.cshtml", 125, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Home/TicketList.cshtml", 125, 17, true);

BeginContext("~/Views/Home/TicketList.cshtml", 142, 4, true);

WriteLiteral(" />\n");

EndContext("~/Views/Home/TicketList.cshtml", 142, 4, true);

BeginContext("~/Views/Home/TicketList.cshtml", 254, 29, true);

WriteLiteral("\n\n<h2>Ticket Management</h2>\n");

EndContext("~/Views/Home/TicketList.cshtml", 254, 29, true);

            
            #line 11 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
 using (Html.BeginForm())
{


            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketList.cshtml", 312, 4, true);

WriteLiteral("<div");

EndContext("~/Views/Home/TicketList.cshtml", 312, 4, true);

BeginContext("~/Views/Home/TicketList.cshtml", 316, 33, true);

WriteLiteral(" class=\"row padingtop-bottom20px\"");

EndContext("~/Views/Home/TicketList.cshtml", 316, 33, true);

BeginContext("~/Views/Home/TicketList.cshtml", 349, 10, true);

WriteLiteral(">\n    <div");

EndContext("~/Views/Home/TicketList.cshtml", 349, 10, true);

BeginContext("~/Views/Home/TicketList.cshtml", 359, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/Home/TicketList.cshtml", 359, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 371, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/TicketList.cshtml", 371, 14, true);

BeginContext("~/Views/Home/TicketList.cshtml", 385, 17, true);

WriteLiteral(" class=\"col-md-2\"");

EndContext("~/Views/Home/TicketList.cshtml", 385, 17, true);

BeginContext("~/Views/Home/TicketList.cshtml", 402, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Home/TicketList.cshtml", 402, 2, true);

BeginContext("~/Views/Home/TicketList.cshtml", 404, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 404, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 417, 130, false);

            
            #line 17 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.EditorFor(model => model.TicketOpenDate, new { htmlAttributes = new { @class = "form-control", placeholder = "From date" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 417, 130, false);

BeginContext("~/Views/Home/TicketList.cshtml", 547, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Home/TicketList.cshtml", 547, 1, true);

BeginContext("~/Views/Home/TicketList.cshtml", 548, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 548, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 561, 92, false);

            
            #line 18 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.ValidationMessageFor(model => model.TicketOpenDate, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 561, 92, false);

BeginContext("~/Views/Home/TicketList.cshtml", 653, 28, true);

WriteLiteral("\n        </div>\n        <div");

EndContext("~/Views/Home/TicketList.cshtml", 653, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 681, 17, true);

WriteLiteral(" class=\"col-md-2\"");

EndContext("~/Views/Home/TicketList.cshtml", 681, 17, true);

BeginContext("~/Views/Home/TicketList.cshtml", 698, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Home/TicketList.cshtml", 698, 2, true);

BeginContext("~/Views/Home/TicketList.cshtml", 700, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 700, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 713, 129, false);

            
            #line 21 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.EditorFor(model => model.TicketCloseDate, new { htmlAttributes = new { @class = "form-control", placeholder = "To date" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 713, 129, false);

BeginContext("~/Views/Home/TicketList.cshtml", 842, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Home/TicketList.cshtml", 842, 1, true);

BeginContext("~/Views/Home/TicketList.cshtml", 843, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 843, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 856, 93, false);

            
            #line 22 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.ValidationMessageFor(model => model.TicketCloseDate, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 856, 93, false);

BeginContext("~/Views/Home/TicketList.cshtml", 949, 29, true);

WriteLiteral("\n        </div>\n\n        <div");

EndContext("~/Views/Home/TicketList.cshtml", 949, 29, true);

BeginContext("~/Views/Home/TicketList.cshtml", 978, 17, true);

WriteLiteral(" class=\"col-md-2\"");

EndContext("~/Views/Home/TicketList.cshtml", 978, 17, true);

BeginContext("~/Views/Home/TicketList.cshtml", 995, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Home/TicketList.cshtml", 995, 2, true);

BeginContext("~/Views/Home/TicketList.cshtml", 997, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 997, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1010, 140, false);

            
            #line 26 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.EditorFor(model => model.CallingNumber, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter calling number" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 1010, 140, false);

BeginContext("~/Views/Home/TicketList.cshtml", 1150, 28, true);

WriteLiteral("\n        </div>\n        <div");

EndContext("~/Views/Home/TicketList.cshtml", 1150, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1178, 17, true);

WriteLiteral(" class=\"col-md-2\"");

EndContext("~/Views/Home/TicketList.cshtml", 1178, 17, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1195, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Home/TicketList.cshtml", 1195, 2, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1197, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 1197, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1210, 130, false);

            
            #line 29 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter customer name" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 1210, 130, false);

BeginContext("~/Views/Home/TicketList.cshtml", 1340, 28, true);

WriteLiteral("\n        </div>\n        <div");

EndContext("~/Views/Home/TicketList.cshtml", 1340, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1368, 17, true);

WriteLiteral(" class=\"col-md-2\"");

EndContext("~/Views/Home/TicketList.cshtml", 1368, 17, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1385, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Home/TicketList.cshtml", 1385, 2, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1387, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 1387, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1400, 138, false);

            
            #line 32 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.EditorFor(model => model.PolicyNumber, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter policy number" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 1400, 138, false);

BeginContext("~/Views/Home/TicketList.cshtml", 1538, 35, true);

WriteLiteral("\n        </div>\n    </div>\n    <div");

EndContext("~/Views/Home/TicketList.cshtml", 1538, 35, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1573, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/Home/TicketList.cshtml", 1573, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1585, 25, true);

WriteLiteral(" style=\"margin-top:10px;\"");

EndContext("~/Views/Home/TicketList.cshtml", 1585, 25, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1610, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/TicketList.cshtml", 1610, 14, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1624, 17, true);

WriteLiteral(" class=\"col-md-2\"");

EndContext("~/Views/Home/TicketList.cshtml", 1624, 17, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1641, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Home/TicketList.cshtml", 1641, 2, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1643, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 1643, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 1656, 686, false);

            
            #line 37 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DropDownListFor(model => model.Status, new SelectList(new[] {new SelectListItem { Text = "Select Status", Value = "Select Status" },
                                                                                new SelectListItem { Text = "Open", Value = "Open" },
                                                                                 new SelectListItem { Text = "InProgress", Value = "InProgress" },
                                                                                 new SelectListItem { Text = "Closed", Value = "Closed" }
                                                                            }, "Text", "Value"), new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 1656, 686, false);

BeginContext("~/Views/Home/TicketList.cshtml", 2342, 28, true);

WriteLiteral("\n        </div>\n        <div");

EndContext("~/Views/Home/TicketList.cshtml", 2342, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2370, 17, true);

WriteLiteral(" class=\"col-md-2\"");

EndContext("~/Views/Home/TicketList.cshtml", 2370, 17, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2387, 20, true);

WriteLiteral(">\n            <input");

EndContext("~/Views/Home/TicketList.cshtml", 2387, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2407, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Home/TicketList.cshtml", 2407, 14, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2421, 14, true);

WriteLiteral(" value=\"Apply\"");

EndContext("~/Views/Home/TicketList.cshtml", 2421, 14, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2435, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/Home/TicketList.cshtml", 2435, 24, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2459, 31, true);

WriteLiteral(" />\n        </div>\n        <div");

EndContext("~/Views/Home/TicketList.cshtml", 2459, 31, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2490, 17, true);

WriteLiteral(" class=\"col-md-8\"");

EndContext("~/Views/Home/TicketList.cshtml", 2490, 17, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2507, 20, true);

WriteLiteral(">\n            <input");

EndContext("~/Views/Home/TicketList.cshtml", 2507, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2527, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/Home/TicketList.cshtml", 2527, 14, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2541, 21, true);

WriteLiteral(" id=\"btnDownladExcel\"");

EndContext("~/Views/Home/TicketList.cshtml", 2541, 21, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2562, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/Home/TicketList.cshtml", 2562, 24, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2586, 23, true);

WriteLiteral(" value=\"Download Excel\"");

EndContext("~/Views/Home/TicketList.cshtml", 2586, 23, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2609, 53, true);

WriteLiteral(" onclick=\"exportToExcel(\'testTable\', \'Excel Export\')\"");

EndContext("~/Views/Home/TicketList.cshtml", 2609, 53, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2662, 20, true);

WriteLiteral(" style=\"float:right\"");

EndContext("~/Views/Home/TicketList.cshtml", 2662, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2682, 16, true);

WriteLiteral(" />\n            ");

EndContext("~/Views/Home/TicketList.cshtml", 2682, 16, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2813, 19, true);

WriteLiteral("\n            <input");

EndContext("~/Views/Home/TicketList.cshtml", 2813, 19, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2832, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/Home/TicketList.cshtml", 2832, 14, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2846, 23, true);

WriteLiteral(" name=\"btnCreateTicket\"");

EndContext("~/Views/Home/TicketList.cshtml", 2846, 23, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2869, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/Home/TicketList.cshtml", 2869, 24, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2893, 22, true);

WriteLiteral(" value=\"Create Ticket\"");

EndContext("~/Views/Home/TicketList.cshtml", 2893, 22, true);

BeginContext("~/Views/Home/TicketList.cshtml", 2915, 39, true);

WriteLiteral(" style=\"float:right;margin-right:10px;\"");

EndContext("~/Views/Home/TicketList.cshtml", 2915, 39, true);

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2954), Tuple.Create("\"", 3022)
, Tuple.Create(Tuple.Create("", 2964), Tuple.Create("window.location=", 2964), true)
, Tuple.Create(Tuple.Create(" ", 2980), Tuple.Create("\'", 2981), true)
            
            #line 49 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
                                                                                        , Tuple.Create(Tuple.Create("", 2982), Tuple.Create<System.Object, System.Int32>(Url.Action("TicketManagement", "Home")
            
            #line default
            #line hidden
, 2982), false)
, Tuple.Create(Tuple.Create("", 3021), Tuple.Create("\'", 3021), true)
);

BeginContext("~/Views/Home/TicketList.cshtml", 3023, 37, true);

WriteLiteral(" />\n        </div>\n    </div>\n</div>\n");

EndContext("~/Views/Home/TicketList.cshtml", 3023, 37, true);

            
            #line 53 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
}

            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketList.cshtml", 3062, 6, true);

WriteLiteral("<table");

EndContext("~/Views/Home/TicketList.cshtml", 3062, 6, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3068, 14, true);

WriteLiteral(" class=\"table\"");

EndContext("~/Views/Home/TicketList.cshtml", 3068, 14, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3082, 15, true);

WriteLiteral(" id=\"testTable\"");

EndContext("~/Views/Home/TicketList.cshtml", 3082, 15, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3097, 24, true);

WriteLiteral(">\n    <tr>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 3097, 24, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3121, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 3121, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3134, 29, false);

            
            #line 57 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Ticket ID"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 3134, 29, false);

BeginContext("~/Views/Home/TicketList.cshtml", 3163, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 3163, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3191, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 3191, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3204, 24, false);

            
            #line 60 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Name"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 3204, 24, false);

BeginContext("~/Views/Home/TicketList.cshtml", 3228, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 3228, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3256, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 3256, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3269, 34, false);

            
            #line 63 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Calling Number"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 3269, 34, false);

BeginContext("~/Views/Home/TicketList.cshtml", 3303, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 3303, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3331, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 3331, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3344, 34, false);

            
            #line 66 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Type Of Caller"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 3344, 34, false);

BeginContext("~/Views/Home/TicketList.cshtml", 3378, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 3378, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3406, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 3406, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3419, 31, false);

            
            #line 69 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Client Type"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 3419, 31, false);

BeginContext("~/Views/Home/TicketList.cshtml", 3450, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 3450, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3478, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 3478, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3491, 33, false);

            
            #line 72 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Policy Number"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 3491, 33, false);

BeginContext("~/Views/Home/TicketList.cshtml", 3524, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 3524, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3552, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 3552, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3565, 27, false);

            
            #line 75 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Segment"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 3565, 27, false);

BeginContext("~/Views/Home/TicketList.cshtml", 3592, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 3592, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3620, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 3620, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3633, 32, false);

            
            #line 78 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Type Of Call"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 3633, 32, false);

BeginContext("~/Views/Home/TicketList.cshtml", 3665, 29, true);

WriteLiteral("\n        </th>\n\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 3665, 29, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3694, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 3694, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3707, 28, false);

            
            #line 82 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Category"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 3707, 28, false);

BeginContext("~/Views/Home/TicketList.cshtml", 3735, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 3735, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3763, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 3763, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3776, 32, false);

            
            #line 85 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Sub Category"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 3776, 32, false);

BeginContext("~/Views/Home/TicketList.cshtml", 3808, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 3808, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3836, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 3836, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3849, 36, false);

            
            #line 88 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Sub Sub Category"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 3849, 36, false);

BeginContext("~/Views/Home/TicketList.cshtml", 3885, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 3885, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3913, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 3913, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3926, 26, false);

            
            #line 91 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Remark"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 3926, 26, false);

BeginContext("~/Views/Home/TicketList.cshtml", 3952, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 3952, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3980, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 3980, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 3993, 26, false);

            
            #line 94 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Status"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 3993, 26, false);

BeginContext("~/Views/Home/TicketList.cshtml", 4019, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 4019, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4047, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 4047, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4060, 36, false);

            
            #line 97 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Ticket Open Date"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 4060, 36, false);

BeginContext("~/Views/Home/TicketList.cshtml", 4096, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 4096, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4124, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 4124, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4137, 37, false);

            
            #line 100 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Ticket Close Date"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 4137, 37, false);

BeginContext("~/Views/Home/TicketList.cshtml", 4174, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 4174, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4202, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 4202, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4215, 37, false);

            
            #line 103 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Ticket Open Agent"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 4215, 37, false);

BeginContext("~/Views/Home/TicketList.cshtml", 4252, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 4252, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4280, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 4280, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4293, 29, false);

            
            #line 106 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Action by"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 4293, 29, false);

BeginContext("~/Views/Home/TicketList.cshtml", 4322, 28, true);

WriteLiteral("\n        </th>\n        <th>\n");

EndContext("~/Views/Home/TicketList.cshtml", 4322, 28, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4350, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/TicketList.cshtml", 4350, 12, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4363, 38, false);

            
            #line 109 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayName("Duration (Minutes)"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 4363, 38, false);

BeginContext("~/Views/Home/TicketList.cshtml", 4401, 54, true);

WriteLiteral("\n        </th>\n        <th>\n\n        </th>\n    </tr>\n\n");

EndContext("~/Views/Home/TicketList.cshtml", 4401, 54, true);

            
            #line 116 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
    
            
            #line default
            #line hidden
            
            #line 116 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
     foreach (var item in Model.TicketList.OrderByDescending(d=>d.TicketOpenDate))
    {

            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketList.cshtml", 4544, 14, true);

WriteLiteral("<tr>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 4544, 14, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4558, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 4558, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4567, 43, false);

            
            #line 120 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.TicketId));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 4567, 43, false);

BeginContext("~/Views/Home/TicketList.cshtml", 4610, 20, true);

WriteLiteral("\n    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 4610, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4630, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 4630, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4639, 39, false);

            
            #line 123 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.Name));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 4639, 39, false);

BeginContext("~/Views/Home/TicketList.cshtml", 4678, 20, true);

WriteLiteral("\n    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 4678, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4698, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 4698, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4707, 48, false);

            
            #line 126 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.CallingNumber));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 4707, 48, false);

BeginContext("~/Views/Home/TicketList.cshtml", 4755, 20, true);

WriteLiteral("\n    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 4755, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4775, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 4775, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4784, 47, false);

            
            #line 129 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.TypeOfCaller));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 4784, 47, false);

BeginContext("~/Views/Home/TicketList.cshtml", 4831, 20, true);

WriteLiteral("\n    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 4831, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4851, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 4851, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4860, 45, false);

            
            #line 132 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.ClientType));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 4860, 45, false);

BeginContext("~/Views/Home/TicketList.cshtml", 4905, 20, true);

WriteLiteral("\n    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 4905, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4925, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 4925, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 4934, 47, false);

            
            #line 135 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.PolicyNumber));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 4934, 47, false);

BeginContext("~/Views/Home/TicketList.cshtml", 4981, 20, true);

WriteLiteral("\n    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 4981, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5001, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 5001, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5010, 50, false);

            
            #line 138 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.CustomerSegment));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 5010, 50, false);

BeginContext("~/Views/Home/TicketList.cshtml", 5060, 20, true);

WriteLiteral("\n    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 5060, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5080, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 5080, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5089, 45, false);

            
            #line 141 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.TypeOfCall));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 5089, 45, false);

BeginContext("~/Views/Home/TicketList.cshtml", 5134, 20, true);

WriteLiteral("\n    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 5134, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5154, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 5154, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5163, 43, false);

            
            #line 144 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.Category));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 5163, 43, false);

BeginContext("~/Views/Home/TicketList.cshtml", 5206, 20, true);

WriteLiteral("\n    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 5206, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5226, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 5226, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5235, 46, false);

            
            #line 147 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.SubCategory));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 5235, 46, false);

BeginContext("~/Views/Home/TicketList.cshtml", 5281, 20, true);

WriteLiteral("\n    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 5281, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5301, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 5301, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5310, 49, false);

            
            #line 150 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.SubSubCategory));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 5310, 49, false);

BeginContext("~/Views/Home/TicketList.cshtml", 5359, 20, true);

WriteLiteral("\n    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 5359, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5379, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 5379, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5388, 41, false);

            
            #line 153 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.Remark));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 5388, 41, false);

BeginContext("~/Views/Home/TicketList.cshtml", 5429, 20, true);

WriteLiteral("\n    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 5429, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5449, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 5449, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5458, 41, false);

            
            #line 156 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.Status));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 5458, 41, false);

BeginContext("~/Views/Home/TicketList.cshtml", 5499, 20, true);

WriteLiteral("\n    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 5499, 20, true);

            
            #line 159 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
        
            
            #line default
            #line hidden
            
            #line 159 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
         if (item.TicketOpenDate != null)
        {
            
            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketList.cshtml", 5584, 49, false);

            
            #line 161 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayFor(modelItem => item.TicketOpenDate));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 5584, 49, false);

            
            #line 161 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
                                                              
        }

            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketList.cshtml", 5644, 19, true);

WriteLiteral("    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 5644, 19, true);

            
            #line 165 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
        
            
            #line default
            #line hidden
            
            #line 165 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
         if (item.TicketCloseDate != null)
        {
            
            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketList.cshtml", 5729, 50, false);

            
            #line 167 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
       Write(Html.DisplayFor(modelItem => item.TicketCloseDate));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 5729, 50, false);

            
            #line 167 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
                                                               
        }

            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketList.cshtml", 5790, 19, true);

WriteLiteral("    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 5790, 19, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5809, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 5809, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5818, 54, false);

            
            #line 171 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.TicketOpenAgentName));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 5818, 54, false);

BeginContext("~/Views/Home/TicketList.cshtml", 5872, 20, true);

WriteLiteral("\n    </td>\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 5872, 20, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5892, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 5892, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5901, 55, false);

            
            #line 174 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.TicketCloseAgentName));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 5901, 55, false);

BeginContext("~/Views/Home/TicketList.cshtml", 5956, 21, true);

WriteLiteral("\n    </td>\n\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 5956, 21, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5977, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/TicketList.cshtml", 5977, 8, true);

BeginContext("~/Views/Home/TicketList.cshtml", 5986, 43, false);

            
            #line 178 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
   Write(Html.DisplayFor(modelItem => item.Duration));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 5986, 43, false);

BeginContext("~/Views/Home/TicketList.cshtml", 6029, 21, true);

WriteLiteral("\n    </td>\n\n    <td>\n");

EndContext("~/Views/Home/TicketList.cshtml", 6029, 21, true);

            
            #line 182 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
        
            
            #line default
            #line hidden
            
            #line 182 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
         if ((item.Status == null) || (item.Status.ToLower() != "closed"))
        {
            if (ViewBag.IsAccess == true)
            {
                
            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketList.cshtml", 6208, 75, false);

            
            #line 186 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
           Write(Html.ActionLink("Edit", "TicketManagementEdit", new { id = item.TicketId }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketList.cshtml", 6208, 75, false);

            
            #line 186 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
                                                                                            
            }

        }

            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketList.cshtml", 6309, 19, true);

WriteLiteral("    </td>\n\n\n\n</tr>\n");

EndContext("~/Views/Home/TicketList.cshtml", 6309, 19, true);

            
            #line 195 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketList.cshtml"
    }

            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketList.cshtml", 6334, 70, true);

WriteLiteral("\n</table>\n<style>\n    .btn {\n        padding: 5px 8px;\n    }\n</style>\n");

EndContext("~/Views/Home/TicketList.cshtml", 6334, 70, true);

DefineSection("Scripts", () => {

BeginContext("~/Views/Home/TicketList.cshtml", 6422, 12, true);

WriteLiteral("\n    <script");

EndContext("~/Views/Home/TicketList.cshtml", 6422, 12, true);

WriteAttribute("src", Tuple.Create(" src=\"", 6434), Tuple.Create("\"", 6462)
, Tuple.Create(Tuple.Create("", 6440), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-ui.js")
, 6440), false)
);

BeginContext("~/Views/Home/TicketList.cshtml", 6463, 22, true);

WriteLiteral("></script>\n    <script");

EndContext("~/Views/Home/TicketList.cshtml", 6463, 22, true);

BeginContext("~/Views/Home/TicketList.cshtml", 6485, 23, true);

WriteLiteral(" type=\"text/javascript\"");

EndContext("~/Views/Home/TicketList.cshtml", 6485, 23, true);

BeginContext("~/Views/Home/TicketList.cshtml", 6508, 3320, true);

WriteLiteral(">\n        $(document).ready(function () {\n\n            //if ($(\"#TicketOpenDate\")" +
".val() == \'01-01-1900 12.00.00 AM\')\n            //    $(\"#TicketOpenDate\").val(\"" +
"\");\n\n            //if ($(\"#TicketCloseDate\").val() == \'01-01-1900 12.00.00 AM\')\n" +
"            //    $(\"#TicketCloseDate\").val(\"\");\n\n            $(\'input[type=date" +
"time]\').datepicker({\n                dateFormat: \"dd/mm/yy\",\n                set" +
"Date: new Date(),\n                changeMonth: true,\n                changeYear:" +
" true\n            });\n\n\n           /* $(\"#btnDownladExcel\").click(function () {\n" +
"                $.ajax(\n                    {\n                        url: \'/Hom" +
"e/TicketDownloadExcel?opendate=\' + $(\"#TicketOpenDate\").val() + \'&closedate=\' + " +
"$(\"#TicketCloseDate\").val() + \'&callingno=\' + $(\"#CallingNumber\").val()+\'&status" +
"=\'+$(\"#Status\").val(),\n                        type: \'GET\',\n                    " +
"    data: \"\",\n                        contentType: \'application/json; charset=ut" +
"f-8\',\n                        success: function (data) {\n                       " +
"     var blob = new Blob([data], { type: \'application/ms-excel\' });\n            " +
"                var downloadUrl = URL.createObjectURL(blob);\n                   " +
"         var a = document.createElement(\"a\");\n                            a.href" +
" = downloadUrl;\n                            a.download = \"TicketListExcel.xls\";\n" +
"                            document.body.appendChild(a);\n                      " +
"      a.click();\n                        },\n                        error: funct" +
"ion () {\n                            alert(\"error\");\n                        }\n " +
"                   });\n\n            });*/\n\n        });\n\n          function expor" +
"tToExcel (table, name) {\n                            var uri = \'data:application" +
"/vnd.ms-excel;base64,\'\n                                ,template = \'<html xmlns:" +
"o=\"urn:schemas-microsoft-com:office:office\" xmlns:x=\"urn:schemas-microsoft-com:o" +
"ffice:excel\" xmlns=\"http://www.w3.org/TR/REC-html40\"><meta http-equiv=\"content-t" +
"ype\" content=\"application/vnd.ms-excel; charset=UTF-8\"><head><!--[if gte mso 9]>" +
"<xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</" +
"x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWo" +
"rksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><ta" +
"ble>{table}</table></body></html>\'\n                                , base64 = fu" +
"nction (s) {\n                                    return window.btoa(unescape(enc" +
"odeURIComponent(s)))\n                                }\n                         " +
"       , format = function (s, c) {\n                                    return s" +
".replace(/{(\\w+)}/g, function (m, p) {\n                                        r" +
"eturn c[p];\n                                    })\n                             " +
"   }\n                            if (!table.nodeType) table = document.getElemen" +
"tById(table)\n                            var ctx = {worksheet: name || \'Workshee" +
"t\', table: table.innerHTML}\n                            var a = document.createE" +
"lement(\'a\');\n                            a.href = uri + base64(format(template, " +
"ctx))\n                            a.download = \'ticketlist.xls\';\n               " +
"             //triggering the function\n                            a.click();\n  " +
"                      }\n\n    </script>\n");

EndContext("~/Views/Home/TicketList.cshtml", 6508, 3320, true);

});

BeginContext("~/Views/Home/TicketList.cshtml", 9830, 2, true);

WriteLiteral("\n\n");

EndContext("~/Views/Home/TicketList.cshtml", 9830, 2, true);

BeginContext("~/Views/Home/TicketList.cshtml", 10140, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Home/TicketList.cshtml", 10140, 1, true);

        }
    }
}
