#pragma checksum "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "13F53064EBA8B62B14C3A107CC0A410C6005A1A4CCDE40625A51EEF8803A1228"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using CallCenterSecure;
    
    
    public class _Page_Views_Home_TicketManagement_cshtml : System.Web.Mvc.WebViewPage<CallCenter.Models.TicketManagementModel> {
        
#line hidden
        
        public _Page_Views_Home_TicketManagement_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
  
    ViewBag.Title = "TicketManagement";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketManagement.cshtml", 138, 8, true);

WriteLiteral("\n<script");

EndContext("~/Views/Home/TicketManagement.cshtml", 138, 8, true);

WriteAttribute("src", Tuple.Create(" src=\"", 146), Tuple.Create("\"", 181)
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-3.3.1.min.js")
, 152), false)
);

BeginContext("~/Views/Home/TicketManagement.cshtml", 182, 36, true);

WriteLiteral("></script>\n\n<h2>Create Ticket</h2>\n\n");

EndContext("~/Views/Home/TicketManagement.cshtml", 182, 36, true);

            
            #line 11 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
 if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
{
    if (ViewBag.Message != null)
    {

            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketManagement.cshtml", 325, 12, true);

WriteLiteral("        <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 325, 12, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 337, 28, true);

WriteLiteral(" class=\"alert alert-success\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 337, 28, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 365, 40, true);

WriteLiteral(">\n            <strong>Success!</strong> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 365, 40, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 406, 15, false);

            
            #line 16 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                                 Write(ViewBag.Message);

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 406, 15, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 421, 16, true);

WriteLiteral("\n        </div>\n");

EndContext("~/Views/Home/TicketManagement.cshtml", 421, 16, true);

            
            #line 18 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
    }
}
else
{

    using (Html.BeginForm("TicketManagement", "Home", FormMethod.Post))
    {
         


            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketManagement.cshtml", 542, 4, true);

WriteLiteral("<div");

EndContext("~/Views/Home/TicketManagement.cshtml", 542, 4, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 546, 24, true);

WriteLiteral(" class=\"form-horizontal\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 546, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 570, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Home/TicketManagement.cshtml", 570, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 572, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Home/TicketManagement.cshtml", 572, 4, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 577, 64, false);

            
            #line 28 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 577, 64, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 641, 9, true);

WriteLiteral("\n    <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 641, 9, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 650, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 650, 23, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 673, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 673, 14, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 687, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 687, 17, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 704, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 704, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 722, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 722, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 740, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 740, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 743, 86, false);

            
            #line 31 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.Label("Name", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 743, 86, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 829, 23, true);

WriteLiteral("</div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 829, 23, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 852, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 852, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 870, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 870, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 873, 93, false);

            
            #line 32 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 873, 93, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 966, 23, true);

WriteLiteral("</div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 966, 23, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 989, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 989, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1007, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 1007, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1010, 98, false);

            
            #line 33 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 1010, 98, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1108, 34, true);

WriteLiteral("</div>\n        </div>\n        <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 1108, 34, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1142, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 1142, 17, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1159, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 1159, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1177, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 1177, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1195, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 1195, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1198, 96, false);

            
            #line 36 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.Label("Calling Number", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 1198, 96, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1294, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 1294, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1318, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 1318, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1336, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 1336, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1339, 102, false);

            
            #line 37 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.EditorFor(model => model.CallingNumber, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 1339, 102, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1441, 23, true);

WriteLiteral("</div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 1441, 23, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1464, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 1464, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1482, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 1482, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1485, 107, false);

            
            #line 38 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.ValidationMessageFor(model => model.CallingNumber, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 1485, 107, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1592, 41, true);

WriteLiteral("</div>\n        </div>\n    </div>\n    <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 1592, 41, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1633, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 1633, 23, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1656, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 1656, 14, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1670, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 1670, 17, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1687, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 1687, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1705, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 1705, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1723, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 1723, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1726, 96, false);

            
            #line 43 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.Label("Type Of Caller", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 1726, 96, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1822, 23, true);

WriteLiteral("</div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 1822, 23, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1845, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 1845, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1863, 22, true);

WriteLiteral(">\n                <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 1863, 22, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1885, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 1885, 17, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1902, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 1902, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 1905, 125, false);

            
            #line 45 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                                  Write(Html.RadioButtonFor(model => model.TypeOfCaller, "Agent", new { @class = "form-control redioButton", @checked = "@checked" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 1905, 125, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2030, 5, true);

WriteLiteral("<span");

EndContext("~/Views/Home/TicketManagement.cshtml", 2030, 5, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2035, 24, true);

WriteLiteral(" class=\"redioButtonText\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 2035, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2059, 41, true);

WriteLiteral(">Agent</span> </div>\n                <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 2059, 41, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2100, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 2100, 17, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2117, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/TicketManagement.cshtml", 2117, 1, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2119, 103, false);

            
            #line 46 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                                 Write(Html.RadioButtonFor(model => model.TypeOfCaller, "Member", new { @class = "form-control redioButton" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 2119, 103, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2222, 5, true);

WriteLiteral("<span");

EndContext("~/Views/Home/TicketManagement.cshtml", 2222, 5, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2227, 24, true);

WriteLiteral(" class=\"redioButtonText\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 2227, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2251, 41, true);

WriteLiteral(">Member</span></div>\n                <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 2251, 41, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2292, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 2292, 17, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2309, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/TicketManagement.cshtml", 2309, 1, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2311, 102, false);

            
            #line 47 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                                 Write(Html.RadioButtonFor(model => model.TypeOfCaller, "Other", new { @class = "form-control redioButton" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 2311, 102, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2413, 5, true);

WriteLiteral("<span");

EndContext("~/Views/Home/TicketManagement.cshtml", 2413, 5, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2418, 24, true);

WriteLiteral(" class=\"redioButtonText\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 2418, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2442, 55, true);

WriteLiteral(">Other</span></div>\n            </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 2442, 55, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2497, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 2497, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2515, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 2515, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2518, 106, false);

            
            #line 49 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.ValidationMessageFor(model => model.TypeOfCaller, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 2518, 106, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2624, 34, true);

WriteLiteral("</div>\n        </div>\n        <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 2624, 34, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2658, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 2658, 17, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2675, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 2675, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2693, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 2693, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2711, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 2711, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2714, 93, false);

            
            #line 52 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.Label("Client Type", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 2714, 93, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2807, 23, true);

WriteLiteral("</div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 2807, 23, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2830, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 2830, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2848, 22, true);

WriteLiteral(">\n                <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 2848, 22, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2870, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 2870, 17, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2887, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 2887, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 2890, 112, false);

            
            #line 54 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                                  Write(Html.RadioButtonFor(model => model.ClientType, "Corporate Solution", new { @class = "form-control redioButton"}));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 2890, 112, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3002, 5, true);

WriteLiteral("<span");

EndContext("~/Views/Home/TicketManagement.cshtml", 3002, 5, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3007, 24, true);

WriteLiteral(" class=\"redioButtonText\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 3007, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3031, 54, true);

WriteLiteral(">Corporate Solution</span> </div>\n                <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 3031, 54, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3085, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 3085, 17, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3102, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/TicketManagement.cshtml", 3102, 1, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3104, 105, false);

            
            #line 55 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                                 Write(Html.RadioButtonFor(model => model.ClientType, "Individual", new { @class = "form-control redioButton" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 3104, 105, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3209, 5, true);

WriteLiteral("<span");

EndContext("~/Views/Home/TicketManagement.cshtml", 3209, 5, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3214, 24, true);

WriteLiteral(" class=\"redioButtonText\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 3214, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3238, 60, true);

WriteLiteral(">Individual</span></div>\n            </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 3238, 60, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3298, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 3298, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3316, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 3316, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3319, 104, false);

            
            #line 57 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.ValidationMessageFor(model => model.ClientType, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 3319, 104, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3423, 41, true);

WriteLiteral("</div>\n        </div>\n    </div>\n    <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 3423, 41, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3464, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 3464, 23, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3487, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 3487, 14, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3501, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 3501, 17, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3518, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 3518, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3536, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 3536, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3554, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 3554, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3557, 95, false);

            
            #line 62 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.Label("Policy Number", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 3557, 95, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3652, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 3652, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3676, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 3676, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3694, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 3694, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3697, 101, false);

            
            #line 63 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.EditorFor(model => model.PolicyNumber, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 3697, 101, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3798, 23, true);

WriteLiteral("</div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 3798, 23, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3821, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 3821, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3839, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 3839, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3842, 106, false);

            
            #line 64 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.ValidationMessageFor(model => model.PolicyNumber, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 3842, 106, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3948, 34, true);

WriteLiteral("</div>\n        </div>\n        <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 3948, 34, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3982, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 3982, 17, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 3999, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 3999, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4017, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 4017, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4035, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 4035, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4038, 89, false);

            
            #line 67 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.Label("Segment", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 4038, 89, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4127, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 4127, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4151, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 4151, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4169, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Home/TicketManagement.cshtml", 4169, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4171, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Home/TicketManagement.cshtml", 4171, 16, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4188, 318, false);

            
            #line 69 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
           Write(Html.DropDownListFor(model => model.CustomerSegment, new List<SelectListItem>
                {
                new SelectListItem{ Text="InternalAgent", Value = "InternalAgent" },
                new SelectListItem{ Text="ExternalAgent", Value = "ExternalAgent" },
                 }, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 4188, 318, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4506, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 4506, 36, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4542, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 4542, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4560, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/TicketManagement.cshtml", 4560, 1, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4562, 109, false);

            
            #line 75 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                              Write(Html.ValidationMessageFor(model => model.CustomerSegment, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 4562, 109, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4671, 42, true);

WriteLiteral("</div>\n        </div>\n    </div>\n\n    <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 4671, 42, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4713, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 4713, 23, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4736, 15, true);

WriteLiteral(">\n\n        <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 4736, 15, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4751, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 4751, 17, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4768, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 4768, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4786, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 4786, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4804, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/TicketManagement.cshtml", 4804, 1, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4806, 94, false);

            
            #line 82 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                              Write(Html.Label("Type Of Call", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 4806, 94, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4900, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 4900, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4924, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 4924, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4942, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Home/TicketManagement.cshtml", 4942, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4944, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Home/TicketManagement.cshtml", 4944, 16, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 4961, 349, false);

            
            #line 84 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
           Write(Html.DropDownListFor(model => model.TypeOfCall, new List<SelectListItem>
           {
               new SelectListItem{ Text="Query", Value = "Query" },
               new SelectListItem{ Text="Request", Value = "Request" },
               new SelectListItem{ Text="Complaint", Value = "Complaint" },
            }, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 4961, 349, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5310, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 5310, 36, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5346, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 5346, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5364, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 5364, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5367, 104, false);

            
            #line 91 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.ValidationMessageFor(model => model.TypeOfCall, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 5367, 104, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5471, 35, true);

WriteLiteral(" </div>\n        </div>\n        <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 5471, 35, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5506, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 5506, 17, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5523, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 5523, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5541, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 5541, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5559, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 5559, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5562, 90, false);

            
            #line 94 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.Label("Category", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 5562, 90, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5652, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 5652, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5676, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 5676, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5694, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 5694, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5697, 144, false);

            
            #line 95 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.DropDownListFor(model => model.Category, new SelectList(Model.CategoryList, "CategoryId", "CategoryName"), new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 5697, 144, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5841, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 5841, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5865, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 5865, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5883, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/TicketManagement.cshtml", 5883, 1, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5885, 102, false);

            
            #line 96 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                              Write(Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 5885, 102, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 5987, 43, true);

WriteLiteral(" </div>\n        </div>\n    </div>\n\n    <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 5987, 43, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6030, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 6030, 23, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6053, 15, true);

WriteLiteral(">\n\n        <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 6053, 15, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6068, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 6068, 17, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6085, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 6085, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6103, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 6103, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6121, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 6121, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6124, 94, false);

            
            #line 103 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.Label("Sub Category", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 6124, 94, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6218, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 6218, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6242, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 6242, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6260, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 6260, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6263, 156, false);

            
            #line 104 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.DropDownListFor(model => model.SubCategory, new SelectList(Model.SubCategoryList, "SubCategoryId", "SubCategoryName"), new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 6263, 156, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6419, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 6419, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6443, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 6443, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6461, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/TicketManagement.cshtml", 6461, 1, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6463, 105, false);

            
            #line 105 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                              Write(Html.ValidationMessageFor(model => model.SubCategory, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 6463, 105, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6568, 35, true);

WriteLiteral(" </div>\n        </div>\n        <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 6568, 35, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6603, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 6603, 17, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6620, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 6620, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6638, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 6638, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6656, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 6656, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6659, 98, false);

            
            #line 108 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.Label("Sub Sub Category", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 6659, 98, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6757, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 6757, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6781, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 6781, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6799, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 6799, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6802, 168, false);

            
            #line 109 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.DropDownListFor(model => model.SubSubCategory, new SelectList(Model.SubSubCategoryList, "SubSubCategoryId", "SubSubCategoryName"), new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 6802, 168, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6970, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 6970, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 6994, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 6994, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7012, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 7012, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7015, 92, false);

            
            #line 110 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.ValidationMessageFor(model => model.SubSubCategory, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 7015, 92, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7107, 43, true);

WriteLiteral(" </div>\n        </div>\n    </div>\n\n    <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 7107, 43, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7150, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 7150, 23, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7173, 22, true);

WriteLiteral(">\n       \n        <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 7173, 22, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7195, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 7195, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7213, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 7213, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7231, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 7231, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7249, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 7249, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7252, 88, false);

            
            #line 117 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.Label("Remark", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 7252, 88, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7340, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 7340, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7364, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 7364, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7382, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 7382, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7385, 113, false);

            
            #line 118 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.EditorFor(model => model.Remark, new { htmlAttributes = new { @class = "form-control paddingBottom10px" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 7385, 113, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7498, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 7498, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7522, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 7522, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7540, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/TicketManagement.cshtml", 7540, 2, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7543, 100, false);

            
            #line 119 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/TicketManagement.cshtml", 7543, 100, false);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7643, 43, true);

WriteLiteral(" </div>\n        </div>\n    </div>\n\n    <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 7643, 43, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7686, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 7686, 23, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7709, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 7709, 14, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7723, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 7723, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7741, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/TicketManagement.cshtml", 7741, 18, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7759, 25, true);

WriteLiteral(" class=\"savecancelbutton\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 7759, 25, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7784, 24, true);

WriteLiteral(">\n                <input");

EndContext("~/Views/Home/TicketManagement.cshtml", 7784, 24, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7808, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 7808, 14, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7822, 13, true);

WriteLiteral(" value=\"Save\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 7822, 13, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7835, 41, true);

WriteLiteral(" class=\"btn btn-primary marginright100px\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 7835, 41, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7876, 26, true);

WriteLiteral(" />\n                <input");

EndContext("~/Views/Home/TicketManagement.cshtml", 7876, 26, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7902, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 7902, 14, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7916, 15, true);

WriteLiteral(" value=\"Cancel\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 7916, 15, true);

BeginContext("~/Views/Home/TicketManagement.cshtml", 7931, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/Home/TicketManagement.cshtml", 7931, 24, true);

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 7955), Tuple.Create("\"", 8018)
, Tuple.Create(Tuple.Create("", 7965), Tuple.Create("window.location=", 7965), true)
, Tuple.Create(Tuple.Create(" ", 7981), Tuple.Create("\'", 7982), true)
            
            #line 127 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
                       , Tuple.Create(Tuple.Create("", 7983), Tuple.Create<System.Object, System.Int32>(Url.Action( "TicketList", "Home")
            
            #line default
            #line hidden
, 7983), false)
, Tuple.Create(Tuple.Create("", 8017), Tuple.Create("\'", 8017), true)
);

BeginContext("~/Views/Home/TicketManagement.cshtml", 8019, 57, true);

WriteLiteral(" />\n\n            </div>\n        </div>\n    </div>\n</div>\n");

EndContext("~/Views/Home/TicketManagement.cshtml", 8019, 57, true);

            
            #line 133 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\TicketManagement.cshtml"
    }
}

            
            #line default
            #line hidden
BeginContext("~/Views/Home/TicketManagement.cshtml", 8084, 2666, true);

WriteLiteral("<script>\n    $(document).ready(function () {\n        $(\"#Category\").on(\"change\", " +
"function () {\n            fillSubCategoryDropdown();\n        });\n        $(\"#Sub" +
"Category\").on(\"change\", function () {\n            fillSubSubCategoryDropdown();\n" +
"        });\n        function fillSubCategoryDropdown() {\n            $.ajax(\n   " +
"             {\n                    url: \'/Home/GetSubCategoryByCategory?Category" +
"Id=\' + $(\"#Category\").val(),\n                    type: \'GET\',\n                  " +
"  data: \"\",\n                    contentType: \'application/json; charset=utf-8\',\n" +
"                    success: function (data) {\n                        var subca" +
"t = $.parseJSON(data);\n                        $(\"#SubCategory\").html(\"\");\n     " +
"                   for (var i = 0; i < subcat.length; i++) {\n                   " +
"         $(\"#SubCategory\").append(\"<option value=\'\" + subcat[i].SubCategoryId + " +
"\"\'>\" + subcat[i].SubCategoryName + \"</option>\");\n                        }\n     " +
"                   fillSubSubCategoryDropdown();\n                    },\n        " +
"            error: function () {\n                        alert(\"error\");\n       " +
"             }\n                })\n        }\n\n        function fillSubSubCategory" +
"Dropdown() {\n            $.ajax(\n                {\n                    url: \'/Ho" +
"me/GetSubSubCategoryBySubCategory?SubCategoryId=\' + $(\"#SubCategory\").val(),\n   " +
"                 type: \'GET\',\n                    data: \"\",\n                    " +
"contentType: \'application/json; charset=utf-8\',\n                    success: fun" +
"ction (data) {\n                        var subcat = $.parseJSON(data);\n         " +
"               $(\"#SubSubCategory\").html(\"\");\n                        for (var i" +
" = 0; i < subcat.length; i++) {\n                            $(\"#SubSubCategory\")" +
".append(\"<option value=\'\" + subcat[i].SubSubCategoryId + \"\'>\" + subcat[i].SubSub" +
"CategoryName + \"</option>\");\n                        }\n                    },\n  " +
"                  error: function () {\n                        alert(\"error\");\n " +
"                   }\n                });\n        }\n\n        $(document).on(\"chan" +
"ge\", \"#TypeOfCaller\", function () {\n\n            $(\"#CustomerSegment\").html(\"\");" +
"\n            if ($(\"#TypeOfCaller:checked\").val() == \"Agent\") {\n                " +
"$(\"#CustomerSegment\").append(\"<option value=\'Primer\'>InternalAgent</option>\");\n " +
"               $(\"#CustomerSegment\").append(\"<option value=\'Elite\'>ExternalAgent" +
"</option>\");\n            }\n            else {\n                $(\"#CustomerSegmen" +
"t\").append(\"<option value=\'Normal\'>Normal</option>\");\n                $(\"#Custom" +
"erSegment\").append(\"<option value=\'Ruby\'>Ruby</option>\");\n            }\n        " +
"});\n\n    });\n</script>\n\n\n");

EndContext("~/Views/Home/TicketManagement.cshtml", 8084, 2666, true);

        }
    }
}
