#pragma checksum "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\Contact.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "61E9FF67BB71B5BE0574A6B0986C328836871CB36562EA429A2BB90440CAB4C4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using CallCenterSecure;
    
    
    public class _Page_Views_Home_Contact_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home_Contact_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\Contact.cshtml"
  
    ViewBag.Title = "Contact";

            
            #line default
            #line hidden
BeginContext("~/Views/Home/Contact.cshtml", 35, 5, true);

WriteLiteral("\n<h2>");

EndContext("~/Views/Home/Contact.cshtml", 35, 5, true);

BeginContext("~/Views/Home/Contact.cshtml", 41, 13, false);

            
            #line 4 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\Contact.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Home/Contact.cshtml", 41, 13, false);

BeginContext("~/Views/Home/Contact.cshtml", 54, 11, true);

WriteLiteral(".</h2>\n<h3>");

EndContext("~/Views/Home/Contact.cshtml", 54, 11, true);

BeginContext("~/Views/Home/Contact.cshtml", 66, 15, false);

            
            #line 5 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\Contact.cshtml"
Write(ViewBag.Message);

            
            #line default
            #line hidden
EndContext("~/Views/Home/Contact.cshtml", 66, 15, false);

BeginContext("~/Views/Home/Contact.cshtml", 81, 87, true);

WriteLiteral("</h3>\n\n<address>\n    One Microsoft Way<br />\n    Redmond, WA 98052-6399<br />\n   " +
" <abbr");

EndContext("~/Views/Home/Contact.cshtml", 81, 87, true);

BeginContext("~/Views/Home/Contact.cshtml", 168, 14, true);

WriteLiteral(" title=\"Phone\"");

EndContext("~/Views/Home/Contact.cshtml", 168, 14, true);

BeginContext("~/Views/Home/Contact.cshtml", 182, 84, true);

WriteLiteral(">P:</abbr>\n    425.555.0100\n</address>\n\n<address>\n    <strong>Support:</strong>  " +
" <a");

EndContext("~/Views/Home/Contact.cshtml", 182, 84, true);

BeginContext("~/Views/Home/Contact.cshtml", 266, 34, true);

WriteLiteral(" href=\"mailto:Support@example.com\"");

EndContext("~/Views/Home/Contact.cshtml", 266, 34, true);

BeginContext("~/Views/Home/Contact.cshtml", 300, 65, true);

WriteLiteral(">Support@example.com</a><br />\n    <strong>Marketing:</strong> <a");

EndContext("~/Views/Home/Contact.cshtml", 300, 65, true);

BeginContext("~/Views/Home/Contact.cshtml", 365, 36, true);

WriteLiteral(" href=\"mailto:Marketing@example.com\"");

EndContext("~/Views/Home/Contact.cshtml", 365, 36, true);

BeginContext("~/Views/Home/Contact.cshtml", 401, 37, true);

WriteLiteral(">Marketing@example.com</a>\n</address>");

EndContext("~/Views/Home/Contact.cshtml", 401, 37, true);

        }
    }
}
