#pragma checksum "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Edit.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "D5D8003F69036C32ECD4FD3CB80D7CFCAD7E2E9AC991E665A3F034315F71AF4F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using CallCenterSecure;
    
    
    public class _Page_Views_Edit_cshtml : System.Web.Mvc.WebViewPage<CallCenter.Models.NatureOfComplaints> {
        
#line hidden
        
        public _Page_Views_Edit_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Edit.cshtml"
  
    ViewBag.Title = "Edit Nature of Complaints";

            
            #line default
            #line hidden
BeginContext("~/Views/Edit.cshtml", 98, 38, true);

WriteLiteral("\n\n<h2>Edit Nature of Complaints</h2>\n\n");

EndContext("~/Views/Edit.cshtml", 98, 38, true);

            
            #line 9 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Edit.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
BeginContext("~/Views/Edit.cshtml", 169, 23, false);

            
            #line 11 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Edit.cshtml", 169, 23, false);

            
            #line 11 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Edit.cshtml"
                            


            
            #line default
            #line hidden
BeginContext("~/Views/Edit.cshtml", 194, 4, true);

WriteLiteral("<div");

EndContext("~/Views/Edit.cshtml", 194, 4, true);

BeginContext("~/Views/Edit.cshtml", 198, 24, true);

WriteLiteral(" class=\"form-horizontal\"");

EndContext("~/Views/Edit.cshtml", 198, 24, true);

BeginContext("~/Views/Edit.cshtml", 222, 47, true);

WriteLiteral(">\n    <h4>Nature of Complaints</h4>\n    <hr />\n");

EndContext("~/Views/Edit.cshtml", 222, 47, true);

BeginContext("~/Views/Edit.cshtml", 269, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Edit.cshtml", 269, 4, true);

BeginContext("~/Views/Edit.cshtml", 274, 64, false);

            
            #line 16 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Edit.cshtml"
Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Edit.cshtml", 274, 64, false);

BeginContext("~/Views/Edit.cshtml", 338, 2, true);

WriteLiteral("\n\n");

EndContext("~/Views/Edit.cshtml", 338, 2, true);

BeginContext("~/Views/Edit.cshtml", 340, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Edit.cshtml", 340, 4, true);

BeginContext("~/Views/Edit.cshtml", 345, 42, false);

            
            #line 18 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Edit.cshtml"
Write(Html.HiddenFor(model => model.ComplaintId));

            
            #line default
            #line hidden
EndContext("~/Views/Edit.cshtml", 345, 42, false);

BeginContext("~/Views/Edit.cshtml", 387, 10, true);

WriteLiteral("\n\n    <div");

EndContext("~/Views/Edit.cshtml", 387, 10, true);

BeginContext("~/Views/Edit.cshtml", 397, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Edit.cshtml", 397, 19, true);

BeginContext("~/Views/Edit.cshtml", 416, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Edit.cshtml", 416, 2, true);

BeginContext("~/Views/Edit.cshtml", 418, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Edit.cshtml", 418, 8, true);

BeginContext("~/Views/Edit.cshtml", 427, 93, false);

            
            #line 21 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Edit.cshtml"
   Write(Html.LabelFor(model => model.ComplaintsDescrption, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
EndContext("~/Views/Edit.cshtml", 427, 93, false);

BeginContext("~/Views/Edit.cshtml", 520, 13, true);

WriteLiteral("\n        <div");

EndContext("~/Views/Edit.cshtml", 520, 13, true);

BeginContext("~/Views/Edit.cshtml", 533, 18, true);

WriteLiteral(" class=\"col-md-10\"");

EndContext("~/Views/Edit.cshtml", 533, 18, true);

BeginContext("~/Views/Edit.cshtml", 551, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Edit.cshtml", 551, 2, true);

BeginContext("~/Views/Edit.cshtml", 553, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Edit.cshtml", 553, 12, true);

BeginContext("~/Views/Edit.cshtml", 566, 109, false);

            
            #line 23 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Edit.cshtml"
       Write(Html.EditorFor(model => model.ComplaintsDescrption, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Edit.cshtml", 566, 109, false);

BeginContext("~/Views/Edit.cshtml", 675, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Edit.cshtml", 675, 1, true);

BeginContext("~/Views/Edit.cshtml", 676, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Edit.cshtml", 676, 12, true);

BeginContext("~/Views/Edit.cshtml", 689, 98, false);

            
            #line 24 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.ComplaintsDescrption, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Edit.cshtml", 689, 98, false);

BeginContext("~/Views/Edit.cshtml", 787, 36, true);

WriteLiteral("\n        </div>\n    </div>\n\n    <div");

EndContext("~/Views/Edit.cshtml", 787, 36, true);

BeginContext("~/Views/Edit.cshtml", 823, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Edit.cshtml", 823, 19, true);

BeginContext("~/Views/Edit.cshtml", 842, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Edit.cshtml", 842, 14, true);

BeginContext("~/Views/Edit.cshtml", 856, 34, true);

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

EndContext("~/Views/Edit.cshtml", 856, 34, true);

BeginContext("~/Views/Edit.cshtml", 890, 20, true);

WriteLiteral(">\n            <input");

EndContext("~/Views/Edit.cshtml", 890, 20, true);

BeginContext("~/Views/Edit.cshtml", 910, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Edit.cshtml", 910, 14, true);

BeginContext("~/Views/Edit.cshtml", 924, 13, true);

WriteLiteral(" value=\"Save\"");

EndContext("~/Views/Edit.cshtml", 924, 13, true);

BeginContext("~/Views/Edit.cshtml", 937, 24, true);

WriteLiteral(" class=\"btn btn-default\"");

EndContext("~/Views/Edit.cshtml", 937, 24, true);

BeginContext("~/Views/Edit.cshtml", 961, 37, true);

WriteLiteral(" />\n        </div>\n    </div>\n</div>\n");

EndContext("~/Views/Edit.cshtml", 961, 37, true);

            
            #line 34 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Edit.cshtml"
}

            
            #line default
            #line hidden
BeginContext("~/Views/Edit.cshtml", 1000, 7, true);

WriteLiteral("\n<div>\n");

EndContext("~/Views/Edit.cshtml", 1000, 7, true);

BeginContext("~/Views/Edit.cshtml", 1007, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Edit.cshtml", 1007, 4, true);

BeginContext("~/Views/Edit.cshtml", 1012, 40, false);

            
            #line 37 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Edit.cshtml"
Write(Html.ActionLink("Back to List", "Index"));

            
            #line default
            #line hidden
EndContext("~/Views/Edit.cshtml", 1012, 40, false);

BeginContext("~/Views/Edit.cshtml", 1052, 9, true);

WriteLiteral("\n</div>\n\n");

EndContext("~/Views/Edit.cshtml", 1052, 9, true);

DefineSection("Scripts", () => {

BeginContext("~/Views/Edit.cshtml", 1079, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Edit.cshtml", 1079, 1, true);

BeginContext("~/Views/Edit.cshtml", 1080, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Edit.cshtml", 1080, 4, true);

BeginContext("~/Views/Edit.cshtml", 1085, 37, false);

            
            #line 41 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Edit.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
EndContext("~/Views/Edit.cshtml", 1085, 37, false);

BeginContext("~/Views/Edit.cshtml", 1122, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Edit.cshtml", 1122, 1, true);

});

        }
    }
}
