#pragma checksum "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\About.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "F0449B0183BBD678734F6E2E889E56DA01286331C00BDAF0C8F070EB2868128D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using CallCenterSecure;
    
    
    public class _Page_Views_Home_About_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home_About_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\About.cshtml"
  
    ViewBag.Title = "About";

            
            #line default
            #line hidden
BeginContext("~/Views/Home/About.cshtml", 33, 5, true);

WriteLiteral("\n<h2>");

EndContext("~/Views/Home/About.cshtml", 33, 5, true);

BeginContext("~/Views/Home/About.cshtml", 39, 13, false);

            
            #line 4 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\About.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Home/About.cshtml", 39, 13, false);

BeginContext("~/Views/Home/About.cshtml", 52, 11, true);

WriteLiteral(".</h2>\n<h3>");

EndContext("~/Views/Home/About.cshtml", 52, 11, true);

BeginContext("~/Views/Home/About.cshtml", 64, 15, false);

            
            #line 5 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\About.cshtml"
Write(ViewBag.Message);

            
            #line default
            #line hidden
EndContext("~/Views/Home/About.cshtml", 64, 15, false);

BeginContext("~/Views/Home/About.cshtml", 79, 63, true);

WriteLiteral("</h3>\n\n<p>Use this area to provide additional information.</p>\n");

EndContext("~/Views/Home/About.cshtml", 79, 63, true);

        }
    }
}
