//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.7.2")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_nzskgy2k {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_nzskgy2k() {
        }
        
        static object Create_ASP__Page_Views_Home_About_cshtml() {
            return new ASP._Page_Views_Home_About_cshtml();
        }
        
        static object Create_ASP__Page_Views_Home_TicketManagementEdit_cshtml() {
            return new ASP._Page_Views_Home_TicketManagementEdit_cshtml();
        }
        
        static object Create_ASP__Page_Views_Home_SRManagementEdit_cshtml() {
            return new ASP._Page_Views_Home_SRManagementEdit_cshtml();
        }
        
        static object Create_ASP__Page_Views_Home_TicketManagement_cshtml() {
            return new ASP._Page_Views_Home_TicketManagement_cshtml();
        }
        
        static object Create_ASP__Page_Views_Home_ResetPassword_cshtml() {
            return new ASP._Page_Views_Home_ResetPassword_cshtml();
        }
        
        static object Create_ASP__Page_Views_Home_KnowledgeCenter_cshtml() {
            return new ASP._Page_Views_Home_KnowledgeCenter_cshtml();
        }
        
        static object Create_ASP__Page_Views_Home_SRList_cshtml() {
            return new ASP._Page_Views_Home_SRList_cshtml();
        }
        
        static object Create_ASP__Page_Views_Home_Index_cshtml() {
            return new ASP._Page_Views_Home_Index_cshtml();
        }
        
        static object Create_ASP__Page_Views_Home_TicketList_cshtml() {
            return new ASP._Page_Views_Home_TicketList_cshtml();
        }
        
        static object Create_ASP__Page_Views_Home_SRManagement_cshtml() {
            return new ASP._Page_Views_Home_SRManagement_cshtml();
        }
        
        static object Create_ASP__Page_Views_Home_Contact_cshtml() {
            return new ASP._Page_Views_Home_Contact_cshtml();
        }
    }
}
