#pragma checksum "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "B28B90DAE8C2F980034C94C7EF9C51594C0EEBBC9CDCD8C44D03B1CB30C8E9B6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using CallCenterSecure;
    
    
    public class _Page_Views_Home_ResetPassword_cshtml : System.Web.Mvc.WebViewPage<CallCenter.Models.RegistrationViewModel> {
        
#line hidden
        
        public _Page_Views_Home_ResetPassword_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
  
    ViewBag.Title = "ResetPassword";

            
            #line default
            #line hidden
BeginContext("~/Views/Home/ResetPassword.cshtml", 89, 27, true);

WriteLiteral("\n\n<h2>Reset Password</h2>\n\n");

EndContext("~/Views/Home/ResetPassword.cshtml", 89, 27, true);

            
            #line 9 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
 using (Html.BeginForm())
{
    

            
            #line default
            #line hidden
BeginContext("~/Views/Home/ResetPassword.cshtml", 149, 4, true);

WriteLiteral("<div");

EndContext("~/Views/Home/ResetPassword.cshtml", 149, 4, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 153, 39, true);

WriteLiteral(" class=\"form-horizontal paddingtop30px\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 153, 39, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 192, 3, true);

WriteLiteral(">\n\n");

EndContext("~/Views/Home/ResetPassword.cshtml", 192, 3, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 195, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Home/ResetPassword.cshtml", 195, 4, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 200, 64, false);

            
            #line 14 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/ResetPassword.cshtml", 200, 64, false);

BeginContext("~/Views/Home/ResetPassword.cshtml", 264, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Home/ResetPassword.cshtml", 264, 1, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 265, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Home/ResetPassword.cshtml", 265, 4, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 270, 37, false);

            
            #line 15 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
Write(Html.HiddenFor(model => model.UserId));

            
            #line default
            #line hidden
EndContext("~/Views/Home/ResetPassword.cshtml", 270, 37, false);

BeginContext("~/Views/Home/ResetPassword.cshtml", 307, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Home/ResetPassword.cshtml", 307, 1, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 308, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Home/ResetPassword.cshtml", 308, 4, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 313, 39, false);

            
            #line 16 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
Write(Html.HiddenFor(model => model.Username));

            
            #line default
            #line hidden
EndContext("~/Views/Home/ResetPassword.cshtml", 313, 39, false);

BeginContext("~/Views/Home/ResetPassword.cshtml", 352, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Home/ResetPassword.cshtml", 352, 1, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 353, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Home/ResetPassword.cshtml", 353, 4, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 358, 40, false);

            
            #line 17 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
Write(Html.HiddenFor(model => model.FirstName));

            
            #line default
            #line hidden
EndContext("~/Views/Home/ResetPassword.cshtml", 358, 40, false);

BeginContext("~/Views/Home/ResetPassword.cshtml", 398, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Home/ResetPassword.cshtml", 398, 1, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 399, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Home/ResetPassword.cshtml", 399, 4, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 404, 39, false);

            
            #line 18 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
Write(Html.HiddenFor(model => model.LastName));

            
            #line default
            #line hidden
EndContext("~/Views/Home/ResetPassword.cshtml", 404, 39, false);

BeginContext("~/Views/Home/ResetPassword.cshtml", 443, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Home/ResetPassword.cshtml", 443, 1, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 444, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Home/ResetPassword.cshtml", 444, 4, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 449, 36, false);

            
            #line 19 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
Write(Html.HiddenFor(model => model.Email));

            
            #line default
            #line hidden
EndContext("~/Views/Home/ResetPassword.cshtml", 449, 36, false);

BeginContext("~/Views/Home/ResetPassword.cshtml", 485, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Home/ResetPassword.cshtml", 485, 1, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 486, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Home/ResetPassword.cshtml", 486, 4, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 491, 37, false);

            
            #line 20 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
Write(Html.HiddenFor(model => model.UserId));

            
            #line default
            #line hidden
EndContext("~/Views/Home/ResetPassword.cshtml", 491, 37, false);

BeginContext("~/Views/Home/ResetPassword.cshtml", 528, 10, true);

WriteLiteral("\n\n    <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 528, 10, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 538, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 538, 23, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 561, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 561, 14, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 575, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 575, 17, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 592, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 592, 18, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 610, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 610, 17, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 627, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/ResetPassword.cshtml", 627, 2, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 630, 73, false);

            
            #line 24 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
                              Write(Html.Label("User Name", htmlAttributes: new { @class = "control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/ResetPassword.cshtml", 630, 73, false);

BeginContext("~/Views/Home/ResetPassword.cshtml", 703, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 703, 24, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 727, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 727, 17, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 744, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/ResetPassword.cshtml", 744, 1, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 746, 121, false);

            
            #line 25 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
                             Write(Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/ResetPassword.cshtml", 746, 121, false);

BeginContext("~/Views/Home/ResetPassword.cshtml", 867, 43, true);

WriteLiteral(" </div>\n        </div>\n    </div>\n\n    <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 867, 43, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 910, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 910, 19, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 929, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 929, 14, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 943, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 943, 17, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 960, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 960, 18, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 978, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 978, 18, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 996, 3, true);

WriteLiteral(">  ");

EndContext("~/Views/Home/ResetPassword.cshtml", 996, 3, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1000, 76, false);

            
            #line 31 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
                                Write(Html.Label("New Password", htmlAttributes: new { @class = "control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/ResetPassword.cshtml", 1000, 76, false);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1076, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 1076, 24, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1100, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 1100, 18, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1118, 4, true);

WriteLiteral(">   ");

EndContext("~/Views/Home/ResetPassword.cshtml", 1118, 4, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1123, 189, false);

            
            #line 32 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
                                 Write(Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @type = "password",@minlength="8",@maxlength="15",@placeholder="Please enter new password" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/ResetPassword.cshtml", 1123, 189, false);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1312, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 1312, 24, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1336, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 1336, 18, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1354, 3, true);

WriteLiteral(">  ");

EndContext("~/Views/Home/ResetPassword.cshtml", 1354, 3, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1358, 102, false);

            
            #line 33 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
                                Write(Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/ResetPassword.cshtml", 1358, 102, false);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1460, 42, true);

WriteLiteral(" </div>\n        </div>\n    </div>\n    <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 1460, 42, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1502, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 1502, 19, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1521, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 1521, 14, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1535, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 1535, 17, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1552, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 1552, 18, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1570, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 1570, 18, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1588, 3, true);

WriteLiteral(">  ");

EndContext("~/Views/Home/ResetPassword.cshtml", 1588, 3, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1592, 80, false);

            
            #line 38 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
                                Write(Html.Label("Confirm Password", htmlAttributes: new { @class = "control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/ResetPassword.cshtml", 1592, 80, false);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1672, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 1672, 24, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1696, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 1696, 18, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1714, 3, true);

WriteLiteral(">  ");

EndContext("~/Views/Home/ResetPassword.cshtml", 1714, 3, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1718, 203, false);

            
            #line 39 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
                                Write(Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control", @type = "password",@minlength="8",@maxlength="15",@placeholder="Please confirm password password" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/ResetPassword.cshtml", 1718, 203, false);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1921, 24, true);

WriteLiteral(" </div>\n            <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 1921, 24, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1945, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 1945, 18, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1963, 3, true);

WriteLiteral(">  ");

EndContext("~/Views/Home/ResetPassword.cshtml", 1963, 3, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 1967, 109, false);

            
            #line 40 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
                                Write(Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/ResetPassword.cshtml", 1967, 109, false);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2076, 41, true);

WriteLiteral("</div>\n        </div>\n    </div>\n    <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 2076, 41, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2117, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2117, 23, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2140, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 2140, 14, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2154, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2154, 17, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2171, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 2171, 18, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2189, 25, true);

WriteLiteral(" class=\"savecancelbutton\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2189, 25, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2214, 24, true);

WriteLiteral(">\n                <input");

EndContext("~/Views/Home/ResetPassword.cshtml", 2214, 24, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2238, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2238, 14, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2252, 13, true);

WriteLiteral(" value=\"Save\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2252, 13, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2265, 41, true);

WriteLiteral(" class=\"btn btn-primary marginright100px\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2265, 41, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2306, 26, true);

WriteLiteral(" />\n                <input");

EndContext("~/Views/Home/ResetPassword.cshtml", 2306, 26, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2332, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2332, 14, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2346, 15, true);

WriteLiteral(" value=\"Cancel\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2346, 15, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2361, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2361, 24, true);

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2385), Tuple.Create("\"", 2443)
, Tuple.Create(Tuple.Create("", 2395), Tuple.Create("window.location=", 2395), true)
, Tuple.Create(Tuple.Create(" ", 2411), Tuple.Create("\'", 2412), true)
            
            #line 47 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
                       , Tuple.Create(Tuple.Create("", 2413), Tuple.Create<System.Object, System.Int32>(Url.Action( "Index", "Home")
            
            #line default
            #line hidden
, 2413), false)
, Tuple.Create(Tuple.Create("", 2442), Tuple.Create("\'", 2442), true)
);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2444, 56, true);

WriteLiteral(" />\n            </div>\n        </div>\n    </div>\n</div>\n");

EndContext("~/Views/Home/ResetPassword.cshtml", 2444, 56, true);

            
            #line 52 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\ResetPassword.cshtml"
}

            
            #line default
            #line hidden
BeginContext("~/Views/Home/ResetPassword.cshtml", 2502, 4, true);

WriteLiteral("<div");

EndContext("~/Views/Home/ResetPassword.cshtml", 2502, 4, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2506, 24, true);

WriteLiteral(" class=\"form-horizontal\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2506, 24, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2530, 10, true);

WriteLiteral(">\n    <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 2530, 10, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2540, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2540, 12, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2552, 36, true);

WriteLiteral(" style=\"font-size: 12px;color: red;\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2552, 36, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2588, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 2588, 14, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2602, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2602, 18, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2620, 40, true);

WriteLiteral(" style=\"font-size:13px;font-weight:bold\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2620, 40, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2660, 38, true);

WriteLiteral("># Password Policy </div>\n        <div");

EndContext("~/Views/Home/ResetPassword.cshtml", 2660, 38, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2698, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2698, 18, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2716, 17, true);

WriteLiteral(">\n            <ul");

EndContext("~/Views/Home/ResetPassword.cshtml", 2716, 17, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2733, 19, true);

WriteLiteral(" class=\"list-group\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2733, 19, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2752, 40, true);

WriteLiteral(" style=\"list-style-type:none !important\"");

EndContext("~/Views/Home/ResetPassword.cshtml", 2752, 40, true);

BeginContext("~/Views/Home/ResetPassword.cshtml", 2792, 320, true);

WriteLiteral(@">
                <li># Minimun password length should be 8 character </li>
                <li># Maximun password length should be 15 character</li>
                <li># Only Alphabets and Numbers allowed</li>
                <li># Minimum Password age 30 days</li>
            </ul>
        </div>
    </div>
</div>

");

EndContext("~/Views/Home/ResetPassword.cshtml", 2792, 320, true);

        }
    }
}
