#pragma checksum "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "ECCF5F9CF100F829D5475478D19B105E7E9513AD90B07363383FB4F7C4DE0D44"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using CallCenterSecure;
    
    
    public class _Page_Views_index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<CallCenter.Models.NatureOfComplaints>> {
        
#line hidden
        
        public _Page_Views_index_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
  
    ViewBag.Title = "Nature of Complaint List";
    int srNo = 1;

            
            #line default
            #line hidden
BeginContext("~/Views/index.cshtml", 128, 41, true);

WriteLiteral("\n\n<h2>Nature of Complaint List</h2>\n\n<p>\n");

EndContext("~/Views/index.cshtml", 128, 41, true);

BeginContext("~/Views/index.cshtml", 169, 4, true);

WriteLiteral("    ");

EndContext("~/Views/index.cshtml", 169, 4, true);

BeginContext("~/Views/index.cshtml", 174, 39, false);

            
            #line 11 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
Write(Html.ActionLink("Create New", "Create"));

            
            #line default
            #line hidden
EndContext("~/Views/index.cshtml", 174, 39, false);

BeginContext("~/Views/index.cshtml", 213, 13, true);

WriteLiteral("\n</p>\n\n<table");

EndContext("~/Views/index.cshtml", 213, 13, true);

BeginContext("~/Views/index.cshtml", 226, 14, true);

WriteLiteral(" class=\"table\"");

EndContext("~/Views/index.cshtml", 226, 14, true);

BeginContext("~/Views/index.cshtml", 240, 72, true);

WriteLiteral(">\n    <thead>\n        <tr>\n            <th>Sr. No.</th>\n            <th>");

EndContext("~/Views/index.cshtml", 240, 72, true);

BeginContext("~/Views/index.cshtml", 313, 47, false);

            
            #line 18 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
           Write(Html.DisplayNameFor(model => model.ComplaintId));

            
            #line default
            #line hidden
EndContext("~/Views/index.cshtml", 313, 47, false);

BeginContext("~/Views/index.cshtml", 360, 22, true);

WriteLiteral("</th>\n            <th>");

EndContext("~/Views/index.cshtml", 360, 22, true);

BeginContext("~/Views/index.cshtml", 383, 56, false);

            
            #line 19 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
           Write(Html.DisplayNameFor(model => model.ComplaintsDescrption));

            
            #line default
            #line hidden
EndContext("~/Views/index.cshtml", 383, 56, false);

BeginContext("~/Views/index.cshtml", 439, 73, true);

WriteLiteral("</th>\n            <th>Action</th>\n        </tr>\n    </thead>\n    <tbody>\n");

EndContext("~/Views/index.cshtml", 439, 73, true);

            
            #line 24 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 24 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
         foreach (var item in Model)
        {

            
            #line default
            #line hidden
BeginContext("~/Views/index.cshtml", 559, 37, true);

WriteLiteral("            <tr>\n                <td>");

EndContext("~/Views/index.cshtml", 559, 37, true);

BeginContext("~/Views/index.cshtml", 597, 4, false);

            
            #line 27 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
               Write(srNo);

            
            #line default
            #line hidden
EndContext("~/Views/index.cshtml", 597, 4, false);

BeginContext("~/Views/index.cshtml", 601, 26, true);

WriteLiteral("</td>\n                <td>");

EndContext("~/Views/index.cshtml", 601, 26, true);

BeginContext("~/Views/index.cshtml", 628, 46, false);

            
            #line 28 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
               Write(Html.DisplayFor(modelItem => item.ComplaintId));

            
            #line default
            #line hidden
EndContext("~/Views/index.cshtml", 628, 46, false);

BeginContext("~/Views/index.cshtml", 674, 26, true);

WriteLiteral("</td>\n                <td>");

EndContext("~/Views/index.cshtml", 674, 26, true);

BeginContext("~/Views/index.cshtml", 701, 55, false);

            
            #line 29 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
               Write(Html.DisplayFor(modelItem => item.ComplaintsDescrption));

            
            #line default
            #line hidden
EndContext("~/Views/index.cshtml", 701, 55, false);

BeginContext("~/Views/index.cshtml", 756, 27, true);

WriteLiteral("</td>\n                <td>\n");

EndContext("~/Views/index.cshtml", 756, 27, true);

BeginContext("~/Views/index.cshtml", 783, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/index.cshtml", 783, 20, true);

BeginContext("~/Views/index.cshtml", 804, 62, false);

            
            #line 31 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
               Write(Html.ActionLink("Edit", "Edit", new { id = item.ComplaintId }));

            
            #line default
            #line hidden
EndContext("~/Views/index.cshtml", 804, 62, false);

BeginContext("~/Views/index.cshtml", 866, 3, true);

WriteLiteral(" |\n");

EndContext("~/Views/index.cshtml", 866, 3, true);

            
            #line 32 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 32 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
                     if (item.IsActive)
                    {
                        
            
            #line default
            #line hidden
BeginContext("~/Views/index.cshtml", 956, 270, false);

            
            #line 34 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
                   Write(Html.ActionLink(
                            "Deactivate",
                            "ToggleActive",
                            "NatureOfComplaints",
                            new { Id = item.ComplaintId },
                            null
                        ));

            
            #line default
            #line hidden
EndContext("~/Views/index.cshtml", 956, 270, false);

            
            #line 40 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
                         
                    }
                    else
                    {
                        
            
            #line default
            #line hidden
BeginContext("~/Views/index.cshtml", 1321, 268, false);

            
            #line 44 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
                   Write(Html.ActionLink(
                            "Activate",
                            "ToggleActive",
                            "NatureOfComplaints",
                            new { Id = item.ComplaintId },
                            null
                        ));

            
            #line default
            #line hidden
EndContext("~/Views/index.cshtml", 1321, 268, false);

            
            #line 50 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
                         
                    }

            
            #line default
            #line hidden
BeginContext("~/Views/index.cshtml", 1612, 40, true);

WriteLiteral("                </td>\n            </tr>\n");

EndContext("~/Views/index.cshtml", 1612, 40, true);

            
            #line 54 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\index.cshtml"
            srNo++;
        }

            
            #line default
            #line hidden
BeginContext("~/Views/index.cshtml", 1682, 22, true);

WriteLiteral("    </tbody>\n</table>\n");

EndContext("~/Views/index.cshtml", 1682, 22, true);

        }
    }
}
