#pragma checksum "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Shared\_DisplayField.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "5E687C313B97C96850E24963186860EA25C330C1DAA930B27EA56F9C55CD3D10"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using CallCenterSecure;
    
    
    public class _Page_Views_Shared__DisplayField_cshtml : System.Web.Mvc.WebViewPage<Tuple<string, object>> {
        
#line hidden
        
        public _Page_Views_Shared__DisplayField_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Shared/_DisplayField.cshtml", 30, 4, true);

WriteLiteral("<div");

EndContext("~/Views/Shared/_DisplayField.cshtml", 30, 4, true);

BeginContext("~/Views/Shared/_DisplayField.cshtml", 34, 22, true);

WriteLiteral(" class=\"col-md-6 mb-2\"");

EndContext("~/Views/Shared/_DisplayField.cshtml", 34, 22, true);

BeginContext("~/Views/Shared/_DisplayField.cshtml", 56, 12, true);

WriteLiteral(">\n    <label");

EndContext("~/Views/Shared/_DisplayField.cshtml", 56, 12, true);

BeginContext("~/Views/Shared/_DisplayField.cshtml", 68, 16, true);

WriteLiteral(" class=\"fw-bold\"");

EndContext("~/Views/Shared/_DisplayField.cshtml", 68, 16, true);

BeginContext("~/Views/Shared/_DisplayField.cshtml", 84, 1, true);

WriteLiteral(">");

EndContext("~/Views/Shared/_DisplayField.cshtml", 84, 1, true);

BeginContext("~/Views/Shared/_DisplayField.cshtml", 86, 11, false);

            
            #line 4 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Shared\_DisplayField.cshtml"
                      Write(Model.Item1);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_DisplayField.cshtml", 86, 11, false);

BeginContext("~/Views/Shared/_DisplayField.cshtml", 97, 17, true);

WriteLiteral("</label>\n    <div");

EndContext("~/Views/Shared/_DisplayField.cshtml", 97, 17, true);

BeginContext("~/Views/Shared/_DisplayField.cshtml", 114, 30, true);

WriteLiteral(" class=\"form-control bg-light\"");

EndContext("~/Views/Shared/_DisplayField.cshtml", 114, 30, true);

BeginContext("~/Views/Shared/_DisplayField.cshtml", 144, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Shared/_DisplayField.cshtml", 144, 2, true);

BeginContext("~/Views/Shared/_DisplayField.cshtml", 146, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Shared/_DisplayField.cshtml", 146, 8, true);

BeginContext("~/Views/Shared/_DisplayField.cshtml", 155, 11, false);

            
            #line 6 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Shared\_DisplayField.cshtml"
   Write(Model.Item2);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_DisplayField.cshtml", 155, 11, false);

BeginContext("~/Views/Shared/_DisplayField.cshtml", 166, 19, true);

WriteLiteral("\n    </div>\n</div>\n");

EndContext("~/Views/Shared/_DisplayField.cshtml", 166, 19, true);

        }
    }
}
