#pragma checksum "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "109D081B2DCA2A917B0DCFAA3880E7DE18D8D4370EFB2F0CBA84E1EBB4D6B7B0"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using CallCenterSecure;
    
    
    public class _Page_Views_AllianceOutbound_Details_cshtml : System.Web.Mvc.WebViewPage<CallCenterSecure.Models.AllianceOutbound> {
        
#line hidden
        
        public _Page_Views_AllianceOutbound_Details_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/AllianceOutbound/Details.cshtml", 0, 1, true);

WriteLiteral("\n");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 0, 1, true);

            
            #line 4 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
  
    ViewBag.Title = "Alliance Inbound Call Details";

            
            #line default
            #line hidden
BeginContext("~/Views/AllianceOutbound/Details.cshtml", 107, 413, true);

WriteLiteral(@"

<style>
    .detail-row {
        display: flex;
        align-items: center;
        margin-bottom: 12px;
    }

    .detail-label {
        width: 180px; /* same width for all labels */
        font-weight: bold;
    }

    .detail-value {
        flex: 1; /* value takes remaining space */
    }
</style>


<h2>Alliance Outbound Call Details</h2>

<div>
    <h4>AllianceOutbound</h4>
    <hr />
    
    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 107, 413, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 520, 18, true);

WriteLiteral(" class=\"container\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 520, 18, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 538, 16, true);

WriteLiteral(">\n        <input");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 538, 16, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 554, 14, true);

WriteLiteral(" type=\"hidden\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 554, 14, true);

WriteAttribute("value", Tuple.Create(" value=\"", 568), Tuple.Create("\"", 595)
            
            #line 33 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
, Tuple.Create(Tuple.Create("", 576), Tuple.Create<System.Object, System.Int32>(ViewBag.TicketType
            
            #line default
            #line hidden
, 576), false)
);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 596, 19, true);

WriteLiteral(" id=\"hdnTicketType\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 596, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 615, 16, true);

WriteLiteral(" />\n        <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 615, 16, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 631, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 631, 12, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 643, 49, true);

WriteLiteral(">\n\n            <!-- Column 1 -->\n            <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 643, 49, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 692, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 692, 17, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 709, 22, true);

WriteLiteral(">\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 709, 22, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 731, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 731, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 750, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 750, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 779, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 779, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 800, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 800, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 802, 40, false);

            
            #line 39 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.CustomerCode));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 802, 40, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 842, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 842, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 877, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 877, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 898, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 898, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 900, 36, false);

            
            #line 40 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.CustomerCode));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 900, 36, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 936, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 936, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 986, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 986, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1005, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1005, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1034, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1034, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1055, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1055, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1057, 47, false);

            
            #line 43 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.CustomerNameEnglish));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 1057, 47, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1104, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1104, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1139, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1139, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1160, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1160, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1162, 43, false);

            
            #line 44 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.CustomerNameEnglish));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 1162, 43, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1205, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1205, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1255, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1255, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1274, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1274, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1303, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1303, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1324, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1324, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1326, 34, false);

            
            #line 47 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.Branch));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 1326, 34, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1360, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1360, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1395, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1395, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1416, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1416, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1418, 30, false);

            
            #line 48 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.Branch));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 1418, 30, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1448, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1448, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1498, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1498, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1517, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1517, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1546, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1546, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1567, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1567, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1569, 39, false);

            
            #line 51 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.StateRegion));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 1569, 39, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1608, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1608, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1643, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1643, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1664, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1664, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1666, 35, false);

            
            #line 52 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.StateRegion));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 1666, 35, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1701, 51, true);

WriteLiteral("</div>\n                </div>\n\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1701, 51, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1752, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1752, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1771, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1771, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1800, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1800, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1821, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1821, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1823, 36, false);

            
            #line 56 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.District));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 1823, 36, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1859, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1859, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1894, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1894, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1915, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1915, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1917, 32, false);

            
            #line 57 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.District));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 1917, 32, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1949, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1949, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 1999, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 1999, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2018, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2018, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2047, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2047, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2068, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2068, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2070, 40, false);

            
            #line 60 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.CityTownship));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 2070, 40, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2110, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2110, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2145, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2145, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2166, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2166, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2168, 36, false);

            
            #line 61 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.CityTownship));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 2168, 36, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2204, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2204, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2254, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2254, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2273, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2273, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2302, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2302, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2323, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2323, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2325, 44, false);

            
            #line 64 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.VillageTractTown));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 2325, 44, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2369, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2369, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2404, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2404, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2425, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2425, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2427, 40, false);

            
            #line 65 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.VillageTractTown));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 2427, 40, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2467, 51, true);

WriteLiteral("</div>\n                </div>\n\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2467, 51, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2518, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2518, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2537, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2537, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2566, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2566, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2587, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2587, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2589, 39, false);

            
            #line 69 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.VillageWard));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 2589, 39, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2628, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2628, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2663, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2663, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2684, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2684, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2686, 35, false);

            
            #line 70 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.VillageWard));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 2686, 35, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2721, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2721, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2771, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2771, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2790, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2790, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2819, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2819, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2840, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2840, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2842, 35, false);

            
            #line 73 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.Address));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 2842, 35, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2877, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2877, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2912, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2912, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2933, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2933, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2935, 31, false);

            
            #line 74 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.Address));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 2935, 31, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 2966, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 2966, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3016, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3016, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3035, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3035, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3064, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3064, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3085, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3085, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3087, 47, false);

            
            #line 77 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.PrimaryMobileNumber));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 3087, 47, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3134, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3134, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3169, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3169, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3190, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3190, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3192, 43, false);

            
            #line 78 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.PrimaryMobileNumber));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 3192, 43, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3235, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3235, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3285, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3285, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3304, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3304, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3333, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3333, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3354, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3354, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3356, 49, false);

            
            #line 81 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.AlternateMobileNumber));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 3356, 49, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3405, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3405, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3440, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3440, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3461, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3461, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3463, 45, false);

            
            #line 82 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.AlternateMobileNumber));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 3463, 45, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3508, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3508, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3558, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3558, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3577, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3577, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3606, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3606, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3627, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3627, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3629, 45, false);

            
            #line 85 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.ProductInterested));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 3629, 45, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3674, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3674, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3709, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3709, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3730, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3730, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3732, 41, false);

            
            #line 86 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.ProductInterested));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 3732, 41, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3773, 97, true);

WriteLiteral("</div>\n                </div>\n\n            </div>\n\n            <!-- Column 2 -->\n" +
"            <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3773, 97, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3870, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3870, 17, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3887, 23, true);

WriteLiteral(">\n\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3887, 23, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3910, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3910, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3929, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3929, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3958, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3958, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3979, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 3979, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 3981, 36, false);

            
            #line 95 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.Latitude));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 3981, 36, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4017, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4017, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4052, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4052, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4073, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4073, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4075, 32, false);

            
            #line 96 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.Latitude));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 4075, 32, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4107, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4107, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4157, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4157, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4176, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4176, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4205, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4205, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4226, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4226, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4228, 37, false);

            
            #line 99 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.Longitude));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 4228, 37, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4265, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4265, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4300, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4300, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4321, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4321, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4323, 33, false);

            
            #line 100 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.Longitude));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 4323, 33, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4356, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4356, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4406, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4406, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4425, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4425, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4454, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4454, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4475, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4475, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4477, 31, false);

            
            #line 103 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.NRC));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 4477, 31, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4508, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4508, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4543, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4543, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4564, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4564, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4566, 27, false);

            
            #line 104 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.NRC));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 4566, 27, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4593, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4593, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4643, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4643, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4662, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4662, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4691, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4691, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4712, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4712, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4714, 39, false);

            
            #line 107 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.DateOfBirth));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 4714, 39, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4753, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4753, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4788, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4788, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4809, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4809, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4811, 35, false);

            
            #line 108 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.DateOfBirth));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 4811, 35, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4846, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4846, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4896, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4896, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4915, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4915, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4944, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4944, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4965, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4965, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4967, 31, false);

            
            #line 111 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.Age));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 4967, 31, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 4998, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 4998, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5033, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5033, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5054, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5054, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5056, 27, false);

            
            #line 112 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.Age));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 5056, 27, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5083, 52, true);

WriteLiteral("</div>\n                </div>\n\n\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5083, 52, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5135, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5135, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5154, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5154, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5183, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5183, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5204, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5204, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5206, 34, false);

            
            #line 117 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.Gender));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 5206, 34, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5240, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5240, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5275, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5275, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5296, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5296, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5298, 30, false);

            
            #line 118 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.Gender));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 5298, 30, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5328, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5328, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5378, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5378, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5397, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5397, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5426, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5426, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5447, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5447, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5449, 41, false);

            
            #line 121 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.MaritalStatus));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 5449, 41, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5490, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5490, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5525, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5525, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5546, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5546, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5548, 37, false);

            
            #line 122 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.MaritalStatus));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 5548, 37, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5585, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5585, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5635, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5635, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5654, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5654, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5683, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5683, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5704, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5704, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5706, 38, false);

            
            #line 125 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.SpouseName));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 5706, 38, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5744, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5744, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5779, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5779, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5800, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5800, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5802, 34, false);

            
            #line 126 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.SpouseName));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 5802, 34, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5836, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5836, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5886, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5886, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5905, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5905, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5934, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5934, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5955, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5955, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5957, 36, false);

            
            #line 129 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.Priority));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 5957, 36, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 5993, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 5993, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6028, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6028, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6049, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6049, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6051, 32, false);

            
            #line 130 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.Priority));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 6051, 32, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6083, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6083, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6133, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6133, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6152, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6152, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6181, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6181, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6202, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6202, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6204, 45, false);

            
            #line 133 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.ClientOfficerName));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 6204, 45, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6249, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6249, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6284, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6284, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6305, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6305, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6307, 41, false);

            
            #line 134 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.ClientOfficerName));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 6307, 41, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6348, 52, true);

WriteLiteral("</div>\n                </div>\n\n\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6348, 52, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6400, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6400, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6419, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6419, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6448, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6448, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6469, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6469, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6471, 38, false);

            
            #line 139 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.CallStatus));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 6471, 38, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6509, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6509, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6544, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6544, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6565, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6565, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6567, 34, false);

            
            #line 140 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.CallStatus));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 6567, 34, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6601, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6601, 50, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6651, 19, true);

WriteLiteral(" class=\"detail-row\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6651, 19, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6670, 29, true);

WriteLiteral(">\n                    <strong");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6670, 29, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6699, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6699, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6720, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6720, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6722, 36, false);

            
            #line 143 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                            Write(Html.DisplayNameFor(m => m.CallType));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 6722, 36, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6758, 35, true);

WriteLiteral(":</strong>\n                    <div");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6758, 35, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6793, 21, true);

WriteLiteral(" class=\"detail-value\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6793, 21, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6814, 1, true);

WriteLiteral(">");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6814, 1, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6816, 32, false);

            
            #line 144 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
                                         Write(Html.DisplayFor(m => m.CallType));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 6816, 32, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 6848, 228, true);

WriteLiteral("</div>\n                </div>\n                \n\n            </div>\n\n            \n" +
"        </div>\n\n        <!-- Lead fields -->\n        \n\n        <!-- CMP fields -" +
"->\n        \n    </div>\n\n\n    <!-- Lead fields -->\n    \n</div>\n\n<p>\n");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 6848, 228, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 7076, 4, true);

WriteLiteral("    ");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 7076, 4, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 7081, 70, false);

            
            #line 166 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
Write(Html.ActionLink("Edit", "Edit", new { id = Model.AllianceOutboundId }));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 7081, 70, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 7151, 3, true);

WriteLiteral(" |\n");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 7151, 3, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 7154, 4, true);

WriteLiteral("    ");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 7154, 4, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 7159, 40, false);

            
            #line 167 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Details.cshtml"
Write(Html.ActionLink("Back to List", "Index"));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Details.cshtml", 7159, 40, false);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 7199, 7, true);

WriteLiteral("\n</p>\n\n");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 7199, 7, true);

DefineSection("Scripts", () => {

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 7224, 12, true);

WriteLiteral("\n    <script");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 7224, 12, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 7236, 23, true);

WriteLiteral(" type=\"text/javascript\"");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 7236, 23, true);

BeginContext("~/Views/AllianceOutbound/Details.cshtml", 7259, 80, true);

WriteLiteral(">\n        $(document).ready(function() {\n            \n        });\n    </script>\n");

EndContext("~/Views/AllianceOutbound/Details.cshtml", 7259, 80, true);

});

        }
    }
}
