#pragma checksum "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\Index.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "0957BE9FFD8729E3AF71F752A62DD060762376053F3B6EFBEE5BC41FC29E04FC"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using CallCenterSecure;
    
    
    public class _Page_Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home_Index_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
BeginContext("~/Views/Home/Index.cshtml", 83, 7, true);

WriteLiteral("\n\n<link");

EndContext("~/Views/Home/Index.cshtml", 83, 7, true);

WriteAttribute("href", Tuple.Create(" href=\"", 90), Tuple.Create("\"", 117)
, Tuple.Create(Tuple.Create("", 97), Tuple.Create<System.Object, System.Int32>(Href("~/Content/c3.min.css")
, 97), false)
);

BeginContext("~/Views/Home/Index.cshtml", 118, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Home/Index.cshtml", 118, 17, true);

BeginContext("~/Views/Home/Index.cshtml", 135, 9, true);

WriteLiteral(" />\n\n<div");

EndContext("~/Views/Home/Index.cshtml", 135, 9, true);

BeginContext("~/Views/Home/Index.cshtml", 144, 35, true);

WriteLiteral(" class=\"home-container text-center\"");

EndContext("~/Views/Home/Index.cshtml", 144, 35, true);

BeginContext("~/Views/Home/Index.cshtml", 179, 12, true);

WriteLiteral(">\n    \n\n    ");

EndContext("~/Views/Home/Index.cshtml", 179, 12, true);

BeginContext("~/Views/Home/Index.cshtml", 262, 5, true);

WriteLiteral("\n    ");

EndContext("~/Views/Home/Index.cshtml", 262, 5, true);

BeginContext("~/Views/Home/Index.cshtml", 4811, 908, true);

WriteLiteral(@"
</div>

<style>
    .home-container {
        min-height: 60vh; /* Ensures space so footer never overlaps */
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    /* Keep original table design when uncommented later */
    .table {
        width: 49% !important;
        border: 1px solid #ddd;
        margin-top: 20px;
        float: left;
        margin-left: 5px;
    }

    td {
        border: 1px solid #ddd;
        font-weight: bold;
    }

    th {
        border: 1px solid #ddd;
        text-align: center;
        background: #0056b3;
        color: #fff;
    }

    .align-center {
        text-align: center;
    }

    .btn-primary {
        background-color: #0056b3;
        border-color: #0056b3;
        color: #fff;
    }

    .btn-selected {
        color: #fff;
        background-color: #0056b3;
        border-color: #0056b3;
    }
</style>
");

EndContext("~/Views/Home/Index.cshtml", 4811, 908, true);

        }
    }
}
