#pragma checksum "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "69C7B3F8F42569BBF2A016097F5E76F80B2DE496FBB66720D6920BE26D35BFB1"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using CallCenterSecure;
    
    
    public class _Page_Views_Home_SRManagement_cshtml : System.Web.Mvc.WebViewPage<CallCenter.Models.SRManagementModel> {
        
#line hidden
        
        public _Page_Views_Home_SRManagement_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
  
    ViewBag.Title = "SRManagement";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
BeginContext("~/Views/Home/SRManagement.cshtml", 130, 8, true);

WriteLiteral("\n<script");

EndContext("~/Views/Home/SRManagement.cshtml", 130, 8, true);

WriteAttribute("src", Tuple.Create(" src=\"", 138), Tuple.Create("\"", 173)
, Tuple.Create(Tuple.Create("", 144), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-3.3.1.min.js")
, 144), false)
);

BeginContext("~/Views/Home/SRManagement.cshtml", 174, 30, true);

WriteLiteral("></script>\n<h2>Create SR</h2>\n");

EndContext("~/Views/Home/SRManagement.cshtml", 174, 30, true);

            
            #line 9 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
 if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
{
    if (ViewBag.Message != null)
    {

            
            #line default
            #line hidden
BeginContext("~/Views/Home/SRManagement.cshtml", 311, 12, true);

WriteLiteral("        <div");

EndContext("~/Views/Home/SRManagement.cshtml", 311, 12, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 323, 28, true);

WriteLiteral(" class=\"alert alert-success\"");

EndContext("~/Views/Home/SRManagement.cshtml", 323, 28, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 351, 40, true);

WriteLiteral(">\n            <strong>Success!</strong> ");

EndContext("~/Views/Home/SRManagement.cshtml", 351, 40, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 392, 15, false);

            
            #line 14 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                 Write(ViewBag.Message);

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 392, 15, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 407, 16, true);

WriteLiteral("\n        </div>\n");

EndContext("~/Views/Home/SRManagement.cshtml", 407, 16, true);

            
            #line 16 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
    }
}
else
{
    using (Html.BeginForm("SRManagement", "Home", FormMethod.Post))
    {



            
            #line default
            #line hidden
BeginContext("~/Views/Home/SRManagement.cshtml", 514, 12, true);

WriteLiteral("        <div");

EndContext("~/Views/Home/SRManagement.cshtml", 514, 12, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 526, 24, true);

WriteLiteral(" class=\"form-horizontal\"");

EndContext("~/Views/Home/SRManagement.cshtml", 526, 24, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 550, 3, true);

WriteLiteral(">\n\n");

EndContext("~/Views/Home/SRManagement.cshtml", 550, 3, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 553, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Home/SRManagement.cshtml", 553, 12, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 566, 64, false);

            
            #line 26 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
       Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 566, 64, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 630, 17, true);

WriteLiteral("\n            <div");

EndContext("~/Views/Home/SRManagement.cshtml", 630, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 647, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/SRManagement.cshtml", 647, 23, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 670, 22, true);

WriteLiteral(">\n                <div");

EndContext("~/Views/Home/SRManagement.cshtml", 670, 22, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 692, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/SRManagement.cshtml", 692, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 709, 26, true);

WriteLiteral(">\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 709, 26, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 735, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 735, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 753, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 753, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 756, 77, false);

            
            #line 29 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.Label("Customer Name", htmlAttributes: new { @class = "control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 756, 77, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 833, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 833, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 865, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 865, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 883, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 883, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 886, 101, false);

            
            #line 30 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 886, 101, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 987, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 987, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1019, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 1019, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1037, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 1037, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1040, 106, false);

            
            #line 31 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 1040, 106, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 1146, 51, true);

WriteLiteral(" </div>\n                </div>\n                <div");

EndContext("~/Views/Home/SRManagement.cshtml", 1146, 51, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1197, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/SRManagement.cshtml", 1197, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1214, 26, true);

WriteLiteral(">\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 1214, 26, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1240, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 1240, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1258, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 1258, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1261, 72, false);

            
            #line 34 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.Label("Phone No", htmlAttributes: new { @class = "control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 1261, 72, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 1333, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 1333, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1365, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 1365, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1383, 3, true);

WriteLiteral(">  ");

EndContext("~/Views/Home/SRManagement.cshtml", 1383, 3, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1387, 96, false);

            
            #line 35 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                        Write(Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 1387, 96, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 1483, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 1483, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1515, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 1515, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1533, 3, true);

WriteLiteral(">  ");

EndContext("~/Views/Home/SRManagement.cshtml", 1533, 3, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1537, 101, false);

            
            #line 36 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                        Write(Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 1537, 101, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 1638, 66, true);

WriteLiteral(" </div>\n                </div>\n            </div>\n            <div");

EndContext("~/Views/Home/SRManagement.cshtml", 1638, 66, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1704, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/SRManagement.cshtml", 1704, 23, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1727, 23, true);

WriteLiteral(">\n\n                <div");

EndContext("~/Views/Home/SRManagement.cshtml", 1727, 23, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1750, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/SRManagement.cshtml", 1750, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1767, 26, true);

WriteLiteral(">\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 1767, 26, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1793, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 1793, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1811, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 1811, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1814, 74, false);

            
            #line 42 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.Label("Agent Name", htmlAttributes: new { @class = "control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 1814, 74, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 1888, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 1888, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1920, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 1920, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1938, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 1938, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 1941, 98, false);

            
            #line 43 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.EditorFor(model => model.AgentName, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 1941, 98, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 2039, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 2039, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2071, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 2071, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2089, 3, true);

WriteLiteral(">  ");

EndContext("~/Views/Home/SRManagement.cshtml", 2089, 3, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2093, 103, false);

            
            #line 44 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                        Write(Html.ValidationMessageFor(model => model.AgentName, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 2093, 103, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 2196, 51, true);

WriteLiteral(" </div>\n                </div>\n                <div");

EndContext("~/Views/Home/SRManagement.cshtml", 2196, 51, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2247, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/SRManagement.cshtml", 2247, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2264, 26, true);

WriteLiteral(">\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 2264, 26, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2290, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 2290, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2308, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 2308, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2311, 93, false);

            
            #line 47 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.Label("Client Type", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 2311, 93, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 2404, 31, true);

WriteLiteral("</div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 2404, 31, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2435, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 2435, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2453, 30, true);

WriteLiteral(">\n                        <div");

EndContext("~/Views/Home/SRManagement.cshtml", 2453, 30, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2483, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/SRManagement.cshtml", 2483, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2500, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 2500, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2503, 113, false);

            
            #line 49 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                          Write(Html.RadioButtonFor(model => model.ClientType, "Corporate Solution", new { @class = "form-control redioButton" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 2503, 113, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 2616, 5, true);

WriteLiteral("<span");

EndContext("~/Views/Home/SRManagement.cshtml", 2616, 5, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2621, 24, true);

WriteLiteral(" class=\"redioButtonText\"");

EndContext("~/Views/Home/SRManagement.cshtml", 2621, 24, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2645, 62, true);

WriteLiteral(">Corporate Solution</span> </div>\n                        <div");

EndContext("~/Views/Home/SRManagement.cshtml", 2645, 62, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2707, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/SRManagement.cshtml", 2707, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2724, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/SRManagement.cshtml", 2724, 1, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2726, 105, false);

            
            #line 50 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                         Write(Html.RadioButtonFor(model => model.ClientType, "Individual", new { @class = "form-control redioButton" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 2726, 105, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 2831, 5, true);

WriteLiteral("<span");

EndContext("~/Views/Home/SRManagement.cshtml", 2831, 5, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2836, 24, true);

WriteLiteral(" class=\"redioButtonText\"");

EndContext("~/Views/Home/SRManagement.cshtml", 2836, 24, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2860, 76, true);

WriteLiteral(">Individual</span></div>\n                    </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 2860, 76, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2936, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 2936, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2954, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 2954, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 2957, 104, false);

            
            #line 52 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.ValidationMessageFor(model => model.ClientType, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 2957, 104, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 3061, 65, true);

WriteLiteral("</div>\n                </div>\n            </div>\n            <div");

EndContext("~/Views/Home/SRManagement.cshtml", 3061, 65, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3126, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/SRManagement.cshtml", 3126, 23, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3149, 22, true);

WriteLiteral(">\n                <div");

EndContext("~/Views/Home/SRManagement.cshtml", 3149, 22, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3171, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/SRManagement.cshtml", 3171, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3188, 26, true);

WriteLiteral(">\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 3188, 26, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3214, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 3214, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3232, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 3232, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3235, 96, false);

            
            #line 57 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.Label("Type Of Caller", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 3235, 96, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 3331, 31, true);

WriteLiteral("</div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 3331, 31, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3362, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 3362, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3380, 30, true);

WriteLiteral(">\n                        <div");

EndContext("~/Views/Home/SRManagement.cshtml", 3380, 30, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3410, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/SRManagement.cshtml", 3410, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3427, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 3427, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3430, 125, false);

            
            #line 59 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                          Write(Html.RadioButtonFor(model => model.TypeOfCaller, "Agent", new { @class = "form-control redioButton", @checked = "@checked" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 3430, 125, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 3555, 5, true);

WriteLiteral("<span");

EndContext("~/Views/Home/SRManagement.cshtml", 3555, 5, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3560, 24, true);

WriteLiteral(" class=\"redioButtonText\"");

EndContext("~/Views/Home/SRManagement.cshtml", 3560, 24, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3584, 49, true);

WriteLiteral(">Agent</span> </div>\n                        <div");

EndContext("~/Views/Home/SRManagement.cshtml", 3584, 49, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3633, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/SRManagement.cshtml", 3633, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3650, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/SRManagement.cshtml", 3650, 1, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3652, 103, false);

            
            #line 60 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                         Write(Html.RadioButtonFor(model => model.TypeOfCaller, "Member", new { @class = "form-control redioButton" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 3652, 103, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 3755, 5, true);

WriteLiteral("<span");

EndContext("~/Views/Home/SRManagement.cshtml", 3755, 5, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3760, 24, true);

WriteLiteral(" class=\"redioButtonText\"");

EndContext("~/Views/Home/SRManagement.cshtml", 3760, 24, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3784, 49, true);

WriteLiteral(">Member</span></div>\n                        <div");

EndContext("~/Views/Home/SRManagement.cshtml", 3784, 49, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3833, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/SRManagement.cshtml", 3833, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3850, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/SRManagement.cshtml", 3850, 1, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3852, 102, false);

            
            #line 61 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                         Write(Html.RadioButtonFor(model => model.TypeOfCaller, "Other", new { @class = "form-control redioButton" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 3852, 102, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 3954, 5, true);

WriteLiteral("<span");

EndContext("~/Views/Home/SRManagement.cshtml", 3954, 5, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3959, 24, true);

WriteLiteral(" class=\"redioButtonText\"");

EndContext("~/Views/Home/SRManagement.cshtml", 3959, 24, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 3983, 71, true);

WriteLiteral(">Other</span></div>\n                    </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 3983, 71, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4054, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 4054, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4072, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 4072, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4075, 106, false);

            
            #line 63 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.ValidationMessageFor(model => model.TypeOfCaller, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 4075, 106, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 4181, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/Home/SRManagement.cshtml", 4181, 50, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4231, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/SRManagement.cshtml", 4231, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4248, 26, true);

WriteLiteral(">\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 4248, 26, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4274, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 4274, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4292, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 4292, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4295, 77, false);

            
            #line 66 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.Label("Issue Details", htmlAttributes: new { @class = "control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 4295, 77, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 4372, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 4372, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4404, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 4404, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4422, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 4422, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4425, 102, false);

            
            #line 67 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.TextAreaFor(model => model.RequestComplaintDetails, new { @class = "form-control", @rows = "4" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 4425, 102, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 4527, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 4527, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4559, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 4559, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4577, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 4577, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4580, 117, false);

            
            #line 68 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.ValidationMessageFor(model => model.RequestComplaintDetails, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 4580, 117, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 4697, 67, true);

WriteLiteral(" </div>\n                </div>\n            </div>\n\n            <div");

EndContext("~/Views/Home/SRManagement.cshtml", 4697, 67, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4764, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/SRManagement.cshtml", 4764, 23, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4787, 22, true);

WriteLiteral(">\n                <div");

EndContext("~/Views/Home/SRManagement.cshtml", 4787, 22, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4809, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/SRManagement.cshtml", 4809, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4826, 26, true);

WriteLiteral(">\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 4826, 26, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4852, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 4852, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4870, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 4870, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4873, 89, false);

            
            #line 74 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.Label("Segment", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 4873, 89, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 4962, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 4962, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 4994, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 4994, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 5012, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Home/SRManagement.cshtml", 5012, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 5014, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Home/SRManagement.cshtml", 5014, 24, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 5039, 350, false);

            
            #line 76 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                   Write(Html.DropDownListFor(model => model.CustomerSegment, new List<SelectListItem>
                        {
                        new SelectListItem{ Text="InternalAgent", Value = "InternalAgent" },
                        new SelectListItem{ Text="ExternalAgent", Value = "ExternalAgent" },
                         }, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 5039, 350, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 5389, 52, true);

WriteLiteral("\n                    </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 5389, 52, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 5441, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 5441, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 5459, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/SRManagement.cshtml", 5459, 1, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 5461, 109, false);

            
            #line 82 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                      Write(Html.ValidationMessageFor(model => model.CustomerSegment, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 5461, 109, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 5570, 50, true);

WriteLiteral("</div>\n                </div>\n                <div");

EndContext("~/Views/Home/SRManagement.cshtml", 5570, 50, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 5620, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/SRManagement.cshtml", 5620, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 5637, 26, true);

WriteLiteral(">\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 5637, 26, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 5663, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 5663, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 5681, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/SRManagement.cshtml", 5681, 1, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 5683, 94, false);

            
            #line 85 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                      Write(Html.Label("Type Of Call", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 5683, 94, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 5777, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 5777, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 5809, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 5809, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 5827, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Home/SRManagement.cshtml", 5827, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 5829, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Home/SRManagement.cshtml", 5829, 24, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 5854, 389, false);

            
            #line 87 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                   Write(Html.DropDownListFor(model => model.TypeOfCall, new List<SelectListItem>
                   {
                       new SelectListItem{ Text="Query", Value = "Query" },
                       new SelectListItem{ Text="Request", Value = "Request" },
                       new SelectListItem{ Text="Complaint", Value = "Complaint" },
                    }, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 5854, 389, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 6243, 52, true);

WriteLiteral("\n                    </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 6243, 52, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6295, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 6295, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6313, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 6313, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6316, 104, false);

            
            #line 94 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.ValidationMessageFor(model => model.TypeOfCall, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 6316, 104, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 6420, 67, true);

WriteLiteral(" </div>\n                </div>\n\n            </div>\n            <div");

EndContext("~/Views/Home/SRManagement.cshtml", 6420, 67, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6487, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/SRManagement.cshtml", 6487, 23, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6510, 55, true);

WriteLiteral(">\n               \n\n            </div>\n\n            <div");

EndContext("~/Views/Home/SRManagement.cshtml", 6510, 55, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6565, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/SRManagement.cshtml", 6565, 23, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6588, 22, true);

WriteLiteral(">\n                <div");

EndContext("~/Views/Home/SRManagement.cshtml", 6588, 22, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6610, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/SRManagement.cshtml", 6610, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6627, 26, true);

WriteLiteral(">\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 6627, 26, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6653, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 6653, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6671, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 6671, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6674, 90, false);

            
            #line 105 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.Label("Category", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 6674, 90, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 6764, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 6764, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6796, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 6796, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6814, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 6814, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6817, 144, false);

            
            #line 106 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.DropDownListFor(model => model.Category, new SelectList(Model.CategoryList, "CategoryId", "CategoryName"), new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 6817, 144, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 6961, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 6961, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 6993, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 6993, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7011, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/SRManagement.cshtml", 7011, 1, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7013, 102, false);

            
            #line 107 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                      Write(Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 7013, 102, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 7115, 51, true);

WriteLiteral(" </div>\n                </div>\n                <div");

EndContext("~/Views/Home/SRManagement.cshtml", 7115, 51, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7166, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/SRManagement.cshtml", 7166, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7183, 26, true);

WriteLiteral(">\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 7183, 26, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7209, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 7209, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7227, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 7227, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7230, 94, false);

            
            #line 110 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.Label("Sub Category", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 7230, 94, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 7324, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 7324, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7356, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 7356, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7374, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 7374, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7377, 156, false);

            
            #line 111 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.DropDownListFor(model => model.SubCategory, new SelectList(Model.SubCategoryList, "SubCategoryId", "SubCategoryName"), new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 7377, 156, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 7533, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 7533, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7565, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 7565, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7583, 1, true);

WriteLiteral(">");

EndContext("~/Views/Home/SRManagement.cshtml", 7583, 1, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7585, 105, false);

            
            #line 112 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                      Write(Html.ValidationMessageFor(model => model.SubCategory, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 7585, 105, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 7690, 67, true);

WriteLiteral(" </div>\n                </div>\n            </div>\n\n            <div");

EndContext("~/Views/Home/SRManagement.cshtml", 7690, 67, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7757, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/SRManagement.cshtml", 7757, 23, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7780, 22, true);

WriteLiteral(">\n                <div");

EndContext("~/Views/Home/SRManagement.cshtml", 7780, 22, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7802, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/SRManagement.cshtml", 7802, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7819, 26, true);

WriteLiteral(">\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 7819, 26, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7845, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 7845, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7863, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 7863, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7866, 98, false);

            
            #line 118 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.Label("Sub Sub Category", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 7866, 98, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 7964, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 7964, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 7996, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 7996, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8014, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 8014, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8017, 168, false);

            
            #line 119 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.DropDownListFor(model => model.SubSubCategory, new SelectList(Model.SubSubCategoryList, "SubSubCategoryId", "SubSubCategoryName"), new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 8017, 168, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 8185, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 8185, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8217, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 8217, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8235, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 8235, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8238, 92, false);

            
            #line 120 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.ValidationMessageFor(model => model.SubSubCategory, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 8238, 92, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 8330, 51, true);

WriteLiteral(" </div>\n                </div>\n                <div");

EndContext("~/Views/Home/SRManagement.cshtml", 8330, 51, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8381, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Home/SRManagement.cshtml", 8381, 17, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8398, 26, true);

WriteLiteral(">\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 8398, 26, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8424, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 8424, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8442, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 8442, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8445, 95, false);

            
            #line 123 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.Label("Policy Number", htmlAttributes: new { @class = "control-label paddingBottom10px" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 8445, 95, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 8540, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 8540, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8572, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 8572, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8590, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 8590, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8593, 113, false);

            
            #line 124 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.EditorFor(model => model.Remark, new { htmlAttributes = new { @class = "form-control paddingBottom10px" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 8593, 113, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 8706, 32, true);

WriteLiteral(" </div>\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 8706, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8738, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 8738, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8756, 2, true);

WriteLiteral("> ");

EndContext("~/Views/Home/SRManagement.cshtml", 8756, 2, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8759, 100, false);

            
            #line 125 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                                       Write(Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger errorMsgPadding" }));

            
            #line default
            #line hidden
EndContext("~/Views/Home/SRManagement.cshtml", 8759, 100, false);

BeginContext("~/Views/Home/SRManagement.cshtml", 8859, 67, true);

WriteLiteral(" </div>\n                </div>\n            </div>\n\n            <div");

EndContext("~/Views/Home/SRManagement.cshtml", 8859, 67, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8926, 23, true);

WriteLiteral(" class=\"form-group row\"");

EndContext("~/Views/Home/SRManagement.cshtml", 8926, 23, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8949, 22, true);

WriteLiteral(">\n                <div");

EndContext("~/Views/Home/SRManagement.cshtml", 8949, 22, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8971, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/Home/SRManagement.cshtml", 8971, 18, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 8989, 26, true);

WriteLiteral(">\n                    <div");

EndContext("~/Views/Home/SRManagement.cshtml", 8989, 26, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 9015, 25, true);

WriteLiteral(" class=\"savecancelbutton\"");

EndContext("~/Views/Home/SRManagement.cshtml", 9015, 25, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 9040, 32, true);

WriteLiteral(">\n                        <input");

EndContext("~/Views/Home/SRManagement.cshtml", 9040, 32, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 9072, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Home/SRManagement.cshtml", 9072, 14, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 9086, 13, true);

WriteLiteral(" value=\"Save\"");

EndContext("~/Views/Home/SRManagement.cshtml", 9086, 13, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 9099, 41, true);

WriteLiteral(" class=\"btn btn-primary marginright100px\"");

EndContext("~/Views/Home/SRManagement.cshtml", 9099, 41, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 9140, 34, true);

WriteLiteral(" />\n                        <input");

EndContext("~/Views/Home/SRManagement.cshtml", 9140, 34, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 9174, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/Home/SRManagement.cshtml", 9174, 14, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 9188, 15, true);

WriteLiteral(" value=\"Cancel\"");

EndContext("~/Views/Home/SRManagement.cshtml", 9188, 15, true);

BeginContext("~/Views/Home/SRManagement.cshtml", 9203, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/Home/SRManagement.cshtml", 9203, 24, true);

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 9227), Tuple.Create("\"", 9286)
, Tuple.Create(Tuple.Create("", 9237), Tuple.Create("window.location=", 9237), true)
, Tuple.Create(Tuple.Create(" ", 9253), Tuple.Create("\'", 9254), true)
            
            #line 133 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
                               , Tuple.Create(Tuple.Create("", 9255), Tuple.Create<System.Object, System.Int32>(Url.Action( "SRList", "Home")
            
            #line default
            #line hidden
, 9255), false)
, Tuple.Create(Tuple.Create("", 9285), Tuple.Create("\'", 9285), true)
);

BeginContext("~/Views/Home/SRManagement.cshtml", 9287, 89, true);

WriteLiteral(" />\n\n                    </div>\n                </div>\n            </div>\n       " +
" </div>\n");

EndContext("~/Views/Home/SRManagement.cshtml", 9287, 89, true);

            
            #line 139 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Home\SRManagement.cshtml"
    }
}

            
            #line default
            #line hidden
BeginContext("~/Views/Home/SRManagement.cshtml", 9384, 2665, true);

WriteLiteral("\n<script>\n    $(document).ready(function () {\n        $(\"#Category\").on(\"change\"," +
" function () {\n            fillSubCategoryDropdown();\n        });\n        $(\"#Su" +
"bCategory\").on(\"change\", function () {\n            fillSubSubCategoryDropdown();" +
"\n        });\n        function fillSubCategoryDropdown() {\n            $.ajax(\n  " +
"              {\n                    url: \'/Home/GetSubCategoryByCategory?Categor" +
"yId=\' + $(\"#Category\").val(),\n                    type: \'GET\',\n                 " +
"   data: \"\",\n                    contentType: \'application/json; charset=utf-8\'," +
"\n                    success: function (data) {\n                        var subc" +
"at = $.parseJSON(data);\n                        $(\"#SubCategory\").html(\"\");\n    " +
"                    for (var i = 0; i < subcat.length; i++) {\n                  " +
"          $(\"#SubCategory\").append(\"<option value=\'\" + subcat[i].SubCategoryId +" +
" \"\'>\" + subcat[i].SubCategoryName + \"</option>\");\n                        }\n    " +
"                    fillSubSubCategoryDropdown();\n                    },\n       " +
"             error: function () {\n                        alert(\"error\");\n      " +
"              }\n                })\n        }\n\n        function fillSubSubCategor" +
"yDropdown() {\n            $.ajax(\n                {\n                    url: \'/H" +
"ome/GetSubSubCategoryBySubCategory?SubCategoryId=\' + $(\"#SubCategory\").val(),\n  " +
"                  type: \'GET\',\n                    data: \"\",\n                   " +
" contentType: \'application/json; charset=utf-8\',\n                    success: fu" +
"nction (data) {\n                        var subcat = $.parseJSON(data);\n        " +
"                $(\"#SubSubCategory\").html(\"\");\n                        for (var " +
"i = 0; i < subcat.length; i++) {\n                            $(\"#SubSubCategory\"" +
").append(\"<option value=\'\" + subcat[i].SubSubCategoryId + \"\'>\" + subcat[i].SubSu" +
"bCategoryName + \"</option>\");\n                        }\n                    },\n " +
"                   error: function () {\n                        alert(\"error\");\n" +
"                    }\n                });\n        }\n\n        $(document).on(\"cha" +
"nge\", \"#TypeOfCaller\", function () {\n\n            $(\"#CustomerSegment\").html(\"\")" +
";\n            if ($(\"#TypeOfCaller:checked\").val() == \"Agent\") {\n               " +
" $(\"#CustomerSegment\").append(\"<option value=\'Primer\'>InternalAgent</option>\");\n" +
"                $(\"#CustomerSegment\").append(\"<option value=\'Elite\'>ExternalAgen" +
"t</option>\");\n            }\n            else {\n                $(\"#CustomerSegme" +
"nt\").append(\"<option value=\'Normal\'>Normal</option>\");\n                $(\"#Custo" +
"merSegment\").append(\"<option value=\'Ruby\'>Ruby</option>\");\n            }\n       " +
" });\n\n    });\n</script>\n");

EndContext("~/Views/Home/SRManagement.cshtml", 9384, 2665, true);

        }
    }
}
