#pragma checksum "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Create.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "2D8DD8311CB4F25C868383F3A5AF660BB12057C2B4690D62477FAD173776C9C6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using CallCenterSecure;
    
    
    public class _Page_Views_Create_cshtml : System.Web.Mvc.WebViewPage<CallCenter.Models.NatureOfComplaints> {
        
#line hidden
        
        public _Page_Views_Create_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Create.cshtml"
  
    ViewBag.Title = "Create Nature of Compalaints";

            
            #line default
            #line hidden
BeginContext("~/Views/Create.cshtml", 101, 41, true);

WriteLiteral("\n\n<h2>Create Nature of Compalaints</h2>\n\n");

EndContext("~/Views/Create.cshtml", 101, 41, true);

            
            #line 9 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Create.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
BeginContext("~/Views/Create.cshtml", 175, 23, false);

            
            #line 11 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Create.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Create.cshtml", 175, 23, false);

            
            #line 11 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Create.cshtml"
                            


            
            #line default
            #line hidden
BeginContext("~/Views/Create.cshtml", 200, 4, true);

WriteLiteral("<div");

EndContext("~/Views/Create.cshtml", 200, 4, true);

BeginContext("~/Views/Create.cshtml", 204, 24, true);

WriteLiteral(" class=\"form-horizontal\"");

EndContext("~/Views/Create.cshtml", 204, 24, true);

BeginContext("~/Views/Create.cshtml", 228, 48, true);

WriteLiteral(">\n    <h4>Complaint Designation</h4>\n    <hr />\n");

EndContext("~/Views/Create.cshtml", 228, 48, true);

BeginContext("~/Views/Create.cshtml", 276, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Create.cshtml", 276, 4, true);

BeginContext("~/Views/Create.cshtml", 281, 64, false);

            
            #line 16 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Create.cshtml"
Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Create.cshtml", 281, 64, false);

BeginContext("~/Views/Create.cshtml", 345, 11, true);

WriteLiteral("\n\n\n    <div");

EndContext("~/Views/Create.cshtml", 345, 11, true);

BeginContext("~/Views/Create.cshtml", 356, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Create.cshtml", 356, 19, true);

BeginContext("~/Views/Create.cshtml", 375, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Create.cshtml", 375, 2, true);

BeginContext("~/Views/Create.cshtml", 377, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Create.cshtml", 377, 8, true);

BeginContext("~/Views/Create.cshtml", 386, 84, false);

            
            #line 20 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Create.cshtml"
   Write(Html.LabelFor(model => model.ComplaintId, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
EndContext("~/Views/Create.cshtml", 386, 84, false);

BeginContext("~/Views/Create.cshtml", 470, 13, true);

WriteLiteral("\n        <div");

EndContext("~/Views/Create.cshtml", 470, 13, true);

BeginContext("~/Views/Create.cshtml", 483, 18, true);

WriteLiteral(" class=\"col-md-10\"");

EndContext("~/Views/Create.cshtml", 483, 18, true);

BeginContext("~/Views/Create.cshtml", 501, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Create.cshtml", 501, 2, true);

BeginContext("~/Views/Create.cshtml", 503, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Create.cshtml", 503, 12, true);

BeginContext("~/Views/Create.cshtml", 516, 100, false);

            
            #line 22 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Create.cshtml"
       Write(Html.EditorFor(model => model.ComplaintId, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Create.cshtml", 516, 100, false);

BeginContext("~/Views/Create.cshtml", 616, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Create.cshtml", 616, 1, true);

BeginContext("~/Views/Create.cshtml", 617, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Create.cshtml", 617, 12, true);

BeginContext("~/Views/Create.cshtml", 630, 89, false);

            
            #line 23 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.ComplaintId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Create.cshtml", 630, 89, false);

BeginContext("~/Views/Create.cshtml", 719, 35, true);

WriteLiteral("\n        </div>\n    </div>\n    <div");

EndContext("~/Views/Create.cshtml", 719, 35, true);

BeginContext("~/Views/Create.cshtml", 754, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Create.cshtml", 754, 19, true);

BeginContext("~/Views/Create.cshtml", 773, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Create.cshtml", 773, 2, true);

BeginContext("~/Views/Create.cshtml", 775, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Create.cshtml", 775, 8, true);

BeginContext("~/Views/Create.cshtml", 784, 93, false);

            
            #line 27 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Create.cshtml"
   Write(Html.LabelFor(model => model.ComplaintsDescrption, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
EndContext("~/Views/Create.cshtml", 784, 93, false);

BeginContext("~/Views/Create.cshtml", 877, 13, true);

WriteLiteral("\n        <div");

EndContext("~/Views/Create.cshtml", 877, 13, true);

BeginContext("~/Views/Create.cshtml", 890, 18, true);

WriteLiteral(" class=\"col-md-10\"");

EndContext("~/Views/Create.cshtml", 890, 18, true);

BeginContext("~/Views/Create.cshtml", 908, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Create.cshtml", 908, 2, true);

BeginContext("~/Views/Create.cshtml", 910, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Create.cshtml", 910, 12, true);

BeginContext("~/Views/Create.cshtml", 923, 109, false);

            
            #line 29 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Create.cshtml"
       Write(Html.EditorFor(model => model.ComplaintsDescrption, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
EndContext("~/Views/Create.cshtml", 923, 109, false);

BeginContext("~/Views/Create.cshtml", 1032, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Create.cshtml", 1032, 1, true);

BeginContext("~/Views/Create.cshtml", 1033, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Create.cshtml", 1033, 12, true);

BeginContext("~/Views/Create.cshtml", 1046, 98, false);

            
            #line 30 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.ComplaintsDescrption, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Create.cshtml", 1046, 98, false);

BeginContext("~/Views/Create.cshtml", 1144, 36, true);

WriteLiteral("\n        </div>\n    </div>\n\n    <div");

EndContext("~/Views/Create.cshtml", 1144, 36, true);

BeginContext("~/Views/Create.cshtml", 1180, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Create.cshtml", 1180, 19, true);

BeginContext("~/Views/Create.cshtml", 1199, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Create.cshtml", 1199, 14, true);

BeginContext("~/Views/Create.cshtml", 1213, 34, true);

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

EndContext("~/Views/Create.cshtml", 1213, 34, true);

BeginContext("~/Views/Create.cshtml", 1247, 20, true);

WriteLiteral(">\n            <input");

EndContext("~/Views/Create.cshtml", 1247, 20, true);

BeginContext("~/Views/Create.cshtml", 1267, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Create.cshtml", 1267, 14, true);

BeginContext("~/Views/Create.cshtml", 1281, 15, true);

WriteLiteral(" value=\"Create\"");

EndContext("~/Views/Create.cshtml", 1281, 15, true);

BeginContext("~/Views/Create.cshtml", 1296, 24, true);

WriteLiteral(" class=\"btn btn-default\"");

EndContext("~/Views/Create.cshtml", 1296, 24, true);

BeginContext("~/Views/Create.cshtml", 1320, 37, true);

WriteLiteral(" />\n        </div>\n    </div>\n</div>\n");

EndContext("~/Views/Create.cshtml", 1320, 37, true);

            
            #line 40 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Create.cshtml"
}

            
            #line default
            #line hidden
BeginContext("~/Views/Create.cshtml", 1359, 7, true);

WriteLiteral("\n<div>\n");

EndContext("~/Views/Create.cshtml", 1359, 7, true);

BeginContext("~/Views/Create.cshtml", 1366, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Create.cshtml", 1366, 4, true);

BeginContext("~/Views/Create.cshtml", 1371, 40, false);

            
            #line 43 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Create.cshtml"
Write(Html.ActionLink("Back to List", "Index"));

            
            #line default
            #line hidden
EndContext("~/Views/Create.cshtml", 1371, 40, false);

BeginContext("~/Views/Create.cshtml", 1411, 9, true);

WriteLiteral("\n</div>\n\n");

EndContext("~/Views/Create.cshtml", 1411, 9, true);

DefineSection("Scripts", () => {

BeginContext("~/Views/Create.cshtml", 1438, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Create.cshtml", 1438, 1, true);

BeginContext("~/Views/Create.cshtml", 1439, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Create.cshtml", 1439, 4, true);

BeginContext("~/Views/Create.cshtml", 1444, 37, false);

            
            #line 47 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Create.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
EndContext("~/Views/Create.cshtml", 1444, 37, false);

BeginContext("~/Views/Create.cshtml", 1481, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Create.cshtml", 1481, 1, true);

});

        }
    }
}
