#pragma checksum "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\Shared\Error.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "07A2AF8FDCB4D1E06E65D098B31F030FECBF7DFF3CA65982BE51FF18773FBAD2"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using CallCenterSecure;
    
    
    public class _Page_Views_Shared_Error_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Shared_Error_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Shared/Error.cshtml", 0, 39, true);

WriteLiteral("<!DOCTYPE html>\n<html>\n<head>\n    <meta");

EndContext("~/Views/Shared/Error.cshtml", 0, 39, true);

BeginContext("~/Views/Shared/Error.cshtml", 39, 16, true);

WriteLiteral(" name=\"viewport\"");

EndContext("~/Views/Shared/Error.cshtml", 39, 16, true);

BeginContext("~/Views/Shared/Error.cshtml", 55, 29, true);

WriteLiteral(" content=\"width=device-width\"");

EndContext("~/Views/Shared/Error.cshtml", 55, 29, true);

BeginContext("~/Views/Shared/Error.cshtml", 84, 177, true);

WriteLiteral(" />\n    <title>Error</title>\n</head>\n<body>\n    <hgroup>\n        <h1>Error.</h1>\n" +
"        <h2>An error occurred while processing your request.</h2>\n    </hgroup>\n" +
"</body>\n</html>\n");

EndContext("~/Views/Shared/Error.cshtml", 84, 177, true);

        }
    }
}
