#pragma checksum "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "147EDF6A3481E4B20C68F84E33803230F2E5D23AD3A4D37E67155ECBBD33FF82"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using CallCenterSecure;
    
    
    public class _Page_Views_AllianceOutbound_Index_cshtml : System.Web.Mvc.WebViewPage<CallCenterSecure.Models.AllianceOutbound> {
        
#line hidden
        
        public _Page_Views_AllianceOutbound_Index_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
  
    ViewBag.Title = "Alliance Outbound Call";

            
            #line default
            #line hidden
BeginContext("~/Views/AllianceOutbound/Index.cshtml", 100, 6, true);

WriteLiteral("\n<link");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 100, 6, true);

WriteAttribute("href", Tuple.Create(" href=\"", 106), Tuple.Create("\"", 136)
, Tuple.Create(Tuple.Create("", 113), Tuple.Create<System.Object, System.Int32>(Href("~/Content/jquery-ui.css")
, 113), false)
);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 137, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 137, 17, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 154, 1511, true);

WriteLiteral(" />\n\n<style>\n    /* DataTable cell content with proper wrapping */\n    table.data" +
"Table tbody td.cell-content {\n        max-width: 10rem; /* wider for readability" +
" */\n        min-width: 8rem;\n        width: auto;\n        overflow: hidden;\n    " +
"    overflow-wrap: break-word;\n        word-wrap: break-word;\n        word-break" +
": break-word;\n        white-space: normal;\n        vertical-align: middle;\n     " +
"   padding: 0.5rem;\n    }\n\n    /* Button cell styling */\n    table.dataTable tbo" +
"dy td.cell-buttons {\n        vertical-align: middle;\n        white-space: nowrap" +
";\n    }\n\n        /* Ensure buttons stay centered */\n        table.dataTable tbod" +
"y td.cell-buttons .btn {\n            margin: 0.2rem;\n        }\n\n    /* General t" +
"able overrides */\n    table.dataTable tbody td {\n        white-space: normal;\n  " +
"      text-align: center;\n        vertical-align: middle;\n    }\n\n    /* Table he" +
"ader text alignment */\n    /*table.dataTable thead th {\n        text-align: cent" +
"er;\n        vertical-align: middle;\n        white-space: nowrap;\n    }*/\n\n    #t" +
"estTable th {\n        white-space: nowrap;\n    }\n    /* Responsive table wrapper" +
" */\n    .table-responsive {\n        overflow-x: auto;\n    }\n\n    .tale thead tr " +
"th {\n        white-space: nowrap;\n    }\n\n    /* Card spacing */\n    .card-body ." +
"row > div {\n        margin-bottom: 0.75rem;\n    }\n\n    /* Fix for DataTables hor" +
"izontal scroll */\n    .dataTables_wrapper .dataTables_scroll {\n        overflow-" +
"x: auto !important;\n    }\n</style>\n\n<h2>Alliance Outbound Calls</h2>\n\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 154, 1511, true);

            
            #line 73 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
 using (Html.BeginForm())
{


            
            #line default
            #line hidden
BeginContext("~/Views/AllianceOutbound/Index.cshtml", 1694, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 1694, 8, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 1702, 33, true);

WriteLiteral(" class=\"row padingtop-bottom20px\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 1702, 33, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 1735, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 1735, 14, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 1749, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 1749, 12, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 1761, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 1761, 18, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 1779, 17, true);

WriteLiteral(" class=\"col-md-2\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 1779, 17, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 1796, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 1796, 2, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 1798, 16, true);

WriteLiteral("                ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 1798, 16, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 1815, 23, false);

            
            #line 79 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
           Write(Html.Label("From Date"));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 1815, 23, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 1838, 1, true);

WriteLiteral("\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 1838, 1, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 1839, 16, true);

WriteLiteral("                ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 1839, 16, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 1856, 125, false);

            
            #line 80 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
           Write(Html.TextBoxFor(m => m.FromDate, new { @class = "form-control datepicker", placeholder = "From Date", autocomplete = "off" }));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 1856, 125, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 1981, 37, true);

WriteLiteral("\n            </div>\n\n            <div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 1981, 37, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2018, 17, true);

WriteLiteral(" class=\"col-md-2\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2018, 17, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2035, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2035, 2, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2037, 16, true);

WriteLiteral("                ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2037, 16, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2054, 21, false);

            
            #line 84 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
           Write(Html.Label("To Date"));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 2054, 21, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2075, 1, true);

WriteLiteral("\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2075, 1, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2076, 16, true);

WriteLiteral("                ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2076, 16, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2093, 121, false);

            
            #line 85 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
           Write(Html.TextBoxFor(m => m.ToDate, new { @class = "form-control datepicker", placeholder = "To Date", autocomplete = "off" }));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 2093, 121, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2214, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2214, 36, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2250, 17, true);

WriteLiteral(" class=\"col-md-2\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2250, 17, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2267, 31, true);

WriteLiteral(">\n                Custmer Code\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2267, 31, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2298, 16, true);

WriteLiteral("                ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2298, 16, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2315, 132, false);

            
            #line 89 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
           Write(Html.EditorFor(model => model.CustomerCode, new { htmlAttributes = new { @class = "form-control", placeholder = "Customer Code" } }));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 2315, 132, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2447, 1, true);

WriteLiteral("\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2447, 1, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2448, 16, true);

WriteLiteral("                ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2448, 16, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2465, 90, false);

            
            #line 90 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
           Write(Html.ValidationMessageFor(model => model.CustomerCode, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 2465, 90, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2555, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2555, 36, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2591, 17, true);

WriteLiteral(" class=\"col-md-2\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2591, 17, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2608, 40, true);

WriteLiteral(">\n                Primary Mobile Number\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2608, 40, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2648, 16, true);

WriteLiteral("                ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2648, 16, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2665, 153, false);

            
            #line 94 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
           Write(Html.EditorFor(model => model.PrimaryMobileNumberSearch, new { htmlAttributes = new { @class = "form-control", placeholder = "Primary Mobile Number" } }));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 2665, 153, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2818, 1, true);

WriteLiteral("\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2818, 1, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2819, 16, true);

WriteLiteral("                ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2819, 16, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2836, 103, false);

            
            #line 95 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
           Write(Html.ValidationMessageFor(model => model.PrimaryMobileNumberSearch, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 2836, 103, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2939, 37, true);

WriteLiteral("\n            </div>\n\n            <div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2939, 37, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2976, 17, true);

WriteLiteral(" class=\"col-md-2\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2976, 17, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 2993, 28, true);

WriteLiteral(">\n                Call Type\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 2993, 28, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 3021, 16, true);

WriteLiteral("                ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 3021, 16, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 3038, 557, false);

            
            #line 100 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
           Write(Html.DropDownListFor(model => model.CallType, new SelectList(new List<SelectListItem>
                                {
                                    new SelectListItem { Value = "Follow Up Call", Text = "Follow Up Call" },
                                    new SelectListItem { Value = "Survey Call", Text = "Survey Call" },
                                    new SelectListItem { Value = "Re-dial Missed Call", Text = "Re-dial Missed Call" }
                                }, "Value", "Text"), "Select CallType", new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 3038, 557, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 3595, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 3595, 36, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 3631, 17, true);

WriteLiteral(" class=\"col-md-2\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 3631, 17, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 3648, 30, true);

WriteLiteral(">\n                Call Status\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 3648, 30, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 3678, 16, true);

WriteLiteral("                ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 3678, 16, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 3695, 416, false);

            
            #line 109 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
           Write(Html.DropDownListFor(model => model.CallStatus, new SelectList(new List<SelectListItem>
                               {
                                   new SelectListItem { Value = "Inactive", Text = "Inactive" },
                                   new SelectListItem { Value = "Active", Text = "Active" }

                               }, "Value", "Text"), "Select CallStatus", new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 3695, 416, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4111, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4111, 36, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4147, 17, true);

WriteLiteral(" class=\"col-md-2\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4147, 17, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4164, 28, true);

WriteLiteral(">\n                Ticket Id\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4164, 28, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4192, 16, true);

WriteLiteral("                ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4192, 16, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4209, 124, false);

            
            #line 118 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
           Write(Html.EditorFor(model => model.TicketID, new { htmlAttributes = new { @class = "form-control", placeholder = "Ticket Id" } }));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 4209, 124, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4333, 1, true);

WriteLiteral("\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4333, 1, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4334, 16, true);

WriteLiteral("                ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4334, 16, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4351, 86, false);

            
            #line 119 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
           Write(Html.ValidationMessageFor(model => model.TicketID, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 4351, 86, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4437, 37, true);

WriteLiteral("\n            </div>\n\n            <div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4437, 37, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4474, 17, true);

WriteLiteral(" class=\"col-md-2\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4474, 17, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4491, 26, true);

WriteLiteral(" style=\"margin-top: 17px;\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4491, 26, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4517, 24, true);

WriteLiteral(">\n                <input");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4517, 24, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4541, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4541, 14, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4555, 14, true);

WriteLiteral(" value=\"Apply\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4555, 14, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4569, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4569, 24, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4593, 21, true);

WriteLiteral(" id=\"btnApplyFilters\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4593, 21, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4614, 52, true);

WriteLiteral(" />\n            </div>\n\n\n        </div>\n        <div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4614, 52, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4666, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4666, 12, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4678, 25, true);

WriteLiteral(" style=\"margin-top:10px;\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4678, 25, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4703, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4703, 18, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4721, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4721, 17, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4738, 22, true);

WriteLiteral(" style=\"float: right;\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4738, 22, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4760, 18, true);

WriteLiteral(">\n                ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4760, 18, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 4946, 17, true);

WriteLiteral("\n                ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 4946, 17, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5171, 24, true);

WriteLiteral("\n                <button");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5171, 24, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5195, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5195, 14, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5209, 48, true);

WriteLiteral("\n                        class=\"btn btn-success\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5209, 48, true);

WriteAttribute("formaction", Tuple.Create("\n                        formaction=\"", 5257), Tuple.Create("\"", 5354)
            
            #line 138 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5294), Tuple.Create<System.Object, System.Int32>(Url.Action("ExportAllianceOutboundCsv", "Allianceoutbound")
            
            #line default
            #line hidden
, 5294), false)
);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5355, 77, true);

WriteLiteral(">\n                    Export\n                </button>\n                <input");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5355, 77, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5432, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5432, 14, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5446, 23, true);

WriteLiteral(" name=\"btnCreateTicket\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5446, 23, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5469, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5469, 24, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5493, 19, true);

WriteLiteral(" value=\"Create New\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5493, 19, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5512, 39, true);

WriteLiteral(" style=\"float:right;margin-right:10px;\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5512, 39, true);

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 5551), Tuple.Create("\"", 5621)
, Tuple.Create(Tuple.Create("", 5561), Tuple.Create("window.location=", 5561), true)
, Tuple.Create(Tuple.Create(" ", 5577), Tuple.Create("\'", 5578), true)
            
            #line 141 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
                                                                                         , Tuple.Create(Tuple.Create("", 5579), Tuple.Create<System.Object, System.Int32>(Url.Action("Create", "AllianceOutbound")
            
            #line default
            #line hidden
, 5579), false)
, Tuple.Create(Tuple.Create("", 5620), Tuple.Create("\'", 5620), true)
);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5622, 49, true);

WriteLiteral(" />\n            </div>\n        </div>\n    </div>\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5622, 49, true);

            
            #line 145 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
}

            
            #line default
            #line hidden
BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5673, 1, true);

WriteLiteral("\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5673, 1, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5718, 5, true);

WriteLiteral("\n<div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5718, 5, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5723, 18, true);

WriteLiteral(" class=\"col-md-12\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5723, 18, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5741, 28, true);

WriteLiteral(" style=\"padding-bottom:10px\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5741, 28, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5769, 7, true);

WriteLiteral(">\n\n    ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5769, 7, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5820, 9, true);

WriteLiteral("\n\n</div>\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5820, 9, true);

            
            #line 153 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
 if (TempData["SuccessMessage"] != null)
{

            
            #line default
            #line hidden
BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5872, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5872, 8, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5880, 67, true);

WriteLiteral(" class=\"alert alert-success alert-dismissible fade show auto-close\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5880, 67, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5947, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5947, 2, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5949, 8, true);

WriteLiteral("        ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5949, 8, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5958, 26, false);

            
            #line 156 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
   Write(TempData["SuccessMessage"]);

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 5958, 26, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 5984, 16, true);

WriteLiteral("\n        <button");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 5984, 16, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6000, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6000, 14, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6014, 18, true);

WriteLiteral(" class=\"btn-close\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6014, 18, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6032, 24, true);

WriteLiteral(" data-bs-dismiss=\"alert\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6032, 24, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6056, 22, true);

WriteLiteral("></button>\n    </div>\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6056, 22, true);

            
            #line 159 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
}

            
            #line default
            #line hidden
            
            #line 160 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
 if (TempData["ErrorMessage"] != null)
{

            
            #line default
            #line hidden
BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6121, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6121, 8, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6129, 66, true);

WriteLiteral(" class=\"alert alert-danger alert-dismissible fade show auto-close\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6129, 66, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6195, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6195, 2, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6197, 8, true);

WriteLiteral("        ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6197, 8, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6206, 24, false);

            
            #line 163 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
   Write(TempData["ErrorMessage"]);

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 6206, 24, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6230, 12, true);

WriteLiteral("\n    </div>\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6230, 12, true);

            
            #line 165 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
}

            
            #line default
            #line hidden
BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6244, 5, true);

WriteLiteral("\n<div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6244, 5, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6249, 28, true);

WriteLiteral(" class=\"card shadow-sm mb-3\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6249, 28, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6277, 10, true);

WriteLiteral(">\n    <div");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6277, 10, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6287, 31, true);

WriteLiteral(" class=\"card-header bg-primary\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6287, 31, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6318, 17, true);

WriteLiteral(">\n        <strong");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6318, 17, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6335, 19, true);

WriteLiteral(" class=\"text-white\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6335, 19, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6354, 38, true);

WriteLiteral(">\n            Outbound Call Records <i");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6354, 38, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6392, 24, true);

WriteLiteral(" class=\"bi bi-card-list\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6392, 24, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6416, 45, true);

WriteLiteral("></i>\n        </strong>\n    </div>\n    <table");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6416, 45, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6461, 19, true);

WriteLiteral(" id=\"outboundTable\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6461, 19, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6480, 72, true);

WriteLiteral(" class=\"table table-bordered table-striped table-hover dataTable nowrap\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6480, 72, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6552, 16, true);

WriteLiteral(">\n        <thead");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6552, 16, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6568, 33, true);

WriteLiteral(" class=\"table-primary text-white\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6568, 33, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6601, 17, true);

WriteLiteral(">\n            <tr");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6601, 17, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6618, 17, true);

WriteLiteral(" id=\"tableHeader\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6618, 17, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6635, 52, true);

WriteLiteral(">\n                <th>Sr No</th>\n                <th");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6635, 52, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6687, 21, true);

WriteLiteral(" style=\"display:none\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6687, 21, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6708, 71, true);

WriteLiteral(">AllianceId</th>\n                <th>Actions</th>\n                <th>\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6708, 71, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6779, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6779, 20, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6800, 29, false);

            
            #line 180 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
               Write(Html.DisplayName("Ticket ID"));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 6800, 29, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6829, 44, true);

WriteLiteral("\n                </th>\n                <th>\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6829, 44, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6873, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6873, 20, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6894, 31, false);

            
            #line 183 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
               Write(Html.DisplayName("Call Status"));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 6894, 31, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6925, 45, true);

WriteLiteral("\n\n                </th>\n                <th>\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6925, 45, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6970, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 6970, 20, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 6991, 29, false);

            
            #line 187 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
               Write(Html.DisplayName("Call Type"));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 6991, 29, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7020, 45, true);

WriteLiteral("\n\n                </th>\n                <th>\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7020, 45, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7065, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7065, 20, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7086, 44, false);

            
            #line 191 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.Priority));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 7086, 44, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7130, 44, true);

WriteLiteral("\n                </th>\n                <th>\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7130, 44, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7174, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7174, 20, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7195, 29, false);

            
            #line 194 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
               Write(Html.DisplayName("Date Time"));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 7195, 29, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7224, 44, true);

WriteLiteral("\n                </th>\n                <th>\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7224, 44, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7268, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7268, 20, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7289, 42, false);

            
            #line 197 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.Branch));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 7289, 42, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7331, 44, true);

WriteLiteral("\n                </th>\n                <th>\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7331, 44, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7375, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7375, 20, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7396, 33, false);

            
            #line 200 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
               Write(Html.DisplayName("Customer Name"));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 7396, 33, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7429, 44, true);

WriteLiteral("\n                </th>\n                <th>\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7429, 44, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7473, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7473, 20, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7494, 32, false);

            
            #line 203 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
               Write(Html.DisplayName("Phone Number"));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 7494, 32, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7526, 44, true);

WriteLiteral("\n                </th>\n                <th>\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7526, 44, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7570, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7570, 20, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7591, 36, false);

            
            #line 206 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
               Write(Html.DisplayName("Product Interest"));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 7591, 36, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7627, 44, true);

WriteLiteral("\n                </th>\n                <th>\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7627, 44, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7671, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7671, 20, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7692, 39, false);

            
            #line 209 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
               Write(Html.DisplayName("Detail Conversation"));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 7692, 39, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7731, 42, true);

WriteLiteral("\n                </th>\n                <th");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7731, 42, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7773, 21, true);

WriteLiteral(" style=\"display:none\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7773, 21, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7794, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7794, 2, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7796, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7796, 20, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7817, 31, false);

            
            #line 212 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
               Write(Html.DisplayName("Ticket Type"));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 7817, 31, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7848, 42, true);

WriteLiteral("\n                </th>\n                <th");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7848, 42, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7890, 21, true);

WriteLiteral(" style=\"display:none\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7890, 21, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7911, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7911, 2, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7913, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7913, 20, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7934, 33, false);

            
            #line 215 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
               Write(Html.DisplayName("Ticket Status"));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 7934, 33, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 7967, 44, true);

WriteLiteral("\n                </th>\n                <th>\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 7967, 44, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 8011, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 8011, 20, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 8032, 37, false);

            
            #line 218 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
               Write(Html.DisplayName("Previous TicketID"));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 8032, 37, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 8069, 86, true);

WriteLiteral("\n                </th>\n            </tr>\n        </thead>\n        <tbody>\n       " +
"     ");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 8069, 86, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 8208, 40, true);

WriteLiteral("\n        </tbody>\n    </table>\n</div>\n\n\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 8208, 40, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 8356, 8, true);

WriteLiteral("\n<script");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 8356, 8, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 8364, 23, true);

WriteLiteral(" type=\"text/javascript\"");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 8364, 23, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 8387, 416, true);

WriteLiteral(@">

    $(document).ready(function () {
        var table = $('#outboundTable').DataTable({
            processing: true,
            serverSide: true,
            pageLength: 10,
            lengthMenu: [10, 20, 50, 100],
            searching: false,
            order: [[1, 'desc']],
            responsive: true,
            fixedHeader: true,
            scrollX: true,
            ajax: {
                url: '");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 8387, 416, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 8804, 50, false);

            
            #line 245 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
                 Write(Url.Action("GetPagedOutbound", "AllianceOutbound"));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 8804, 50, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 8854, 1074, true);

WriteLiteral(@"',
                type: 'POST',
                data: function (d) {
                    d.FromDate = $('#FromDate').val();
                    d.ToDate = $('#ToDate').val();
                    d.CustomerCode = $('#CustomerCode').val();
                    d.PrimaryMobileNumberSearch = $('#PrimaryMobileNumberSearch').val();
                    d.CallType = $('#CallType').val();
                    d.CallStatus = $('#CallStatus').val();
                    d.TicketID = $('#TicketID').val();
                }
            },
            columns: [
                {
                    data: null,
                    orderable: false,
                    render: function (data, type, row, meta) {
                        return meta.settings._iDisplayStart + meta.row + 1;
                    }
                },
                { data: 'AllianceOutboundId', visible: false },
                {
                    data: 'AllianceOutboundId',
                    orderable: false,
                    render: function (data) {
                        var editUrl = '");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 8854, 1074, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 9929, 61, false);

            
            #line 270 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
                                  Write(Url.Action("Edit", "AllianceOutbound", new { id = "__id__" }));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 9929, 61, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 9990, 69, true);

WriteLiteral("\'.replace(\'__id__\', data);\n                        var detailsUrl = \'");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 9990, 69, true);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 10060, 64, false);

            
            #line 271 "D:\Deployment\Alliance-CRM-main\Alliance-CRM-main\CallCenterSecure\Views\AllianceOutbound\Index.cshtml"
                                     Write(Url.Action("Details", "AllianceOutbound", new { id = "__id__" }));

            
            #line default
            #line hidden
EndContext("~/Views/AllianceOutbound/Index.cshtml", 10060, 64, false);

BeginContext("~/Views/AllianceOutbound/Index.cshtml", 10124, 2814, true);

WriteLiteral("\'.replace(\'__id__\', data);\n                        return \'<a href=\"\' + editUrl +" +
" \'\">Edit</a> | <a href=\"\' + detailsUrl + \'\">Details</a>\';\n                    }\n" +
"                },\n                { data: \'TicketID\' },\n                { data:" +
" \'CallStatus\' },\n                { data: \'CallType\' },\n                { data: \'" +
"Priority\' },\n                { data: \'DateTime\' },\n                { data: \'Bran" +
"chName\' },\n                { data: \'CustomerNameEnglish\' },\n                { da" +
"ta: \'PrimaryMobileNumber\' },\n                { data: \'ProductInterestedName\' },\n" +
"                {\n                    data: \'DetailConversation\',\n              " +
"      render: function (data) {\n                        if (!data) return \'\';\n  " +
"                      return data.length > 20 ? data.substring(0, 20) + \'...\' : " +
"data;\n                    }\n                },\n                { data: null, vis" +
"ible: false, defaultContent: \'\' },\n                { data: null, visible: false," +
" defaultContent: \'\' },\n                { data: \'Prev_TicketId\' }\n            ]\n " +
"       });\n\n        $(\'#btnApplyFilters\').on(\'click\', function () {\n            " +
"table.ajax.reload();\n        });\n    });\n\n    $(function () {\n        $(\".datepi" +
"cker\").datepicker({\n            dateFormat: \"yy-mm-dd\",\n            changeMonth:" +
" true,\n            changeYear: true,\n            autoclose: true\n        });\n   " +
" });\n\n    function exportToExcel(table, name) {\n        var uri = \'data:applicat" +
"ion/vnd.ms-excel;base64,\'\n            , template = \'<html xmlns:o=\"urn:schemas-m" +
"icrosoft-com:office:office\" xmlns:x=\"urn:schemas-microsoft-com:office:excel\" xml" +
"ns=\"http://www.w3.org/TR/REC-html40\"><meta http-equiv=\"content-type\" content=\"ap" +
"plication/vnd.ms-excel; charset=UTF-8\"><head><!--[if gte mso 9]><xml><x:ExcelWor" +
"kbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:Worksh" +
"eetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:Exce" +
"lWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</tab" +
"le></body></html>\'\n            , base64 = function (s) {\n                return " +
"window.btoa(unescape(encodeURIComponent(s)))\n            }\n            , format " +
"= function (s, c) {\n                return s.replace(/{(\\w+)}/g, function (m, p)" +
" {\n                    return c[p];\n                })\n            }\n        if " +
"(!table.nodeType) table = document.getElementById(table)\n        var ctx = { wor" +
"ksheet: name || \'Worksheet\', table: table.innerHTML }\n        var a = document.c" +
"reateElement(\'a\');\n        a.href = uri + base64(format(template, ctx))\n        " +
"a.download = \'AllianceOutBound.xls\';\n        a.download = \'AllianceOutBound.xls\'" +
";\n        //triggering the function\n        a.click();\n    }\n    setTimeout(func" +
"tion () {\n        $(\'.auto-close\').fadeOut(\'slow\');\n    }, 3000); // 3 seconds\n\n" +
"\n\n</script>\n\n");

EndContext("~/Views/AllianceOutbound/Index.cshtml", 10124, 2814, true);

        }
    }
}
