// <auto-generated />
namespace CallCenter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Outbound_Detail_Conversation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Outbound_Detail_Conversation));
        
        string IMigrationMetadata.Id
        {
            get { return "202512151805441_Outbound_Detail_Conversation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
